### ISSUE TITLE
关于加载loading和数据为空时View显示问题

### ISSUE THREAD

**Issue by hnrainll** [Jude95/EasyRecyclerView#1]
在EasyRecyclerView的lib中没有指定默认的loading和为空时的View。如果使用者忘记添加避免app:layout_empty="@layout/view_empty"
app:layout_progress="@layout/view_progress"

则会crash，建议在lib中添加默认view。

且：
//生成空白View
        mEmpty = (ViewStub) v.findViewById(R.id.empty);
        mEmpty.setLayoutResource(mEmptyId);
        if (mEmptyId != 0)
            mEmptyView = mEmpty.inflate();

有bug。

**Comment by Jude95** [comment]
@hnrainll 感谢指出，已修复。不过不应该设置默认view，默认view的话，不会好看，也没办法取消使用progress与empty的的功能。还是不填写就没有这2个功能更好。

**Comment by zyyoona7** [comment]
EasyRecyclerView的建议，希望在VIewHolder中添加EasyRecyclerView的item点击事件和里面子view的点击事件，onClick和LongClick
