### ISSUE TITLE
自定义dialog

### ISSUE THREAD

**Issue by star-andy** [Jude95/EasyRecyclerView#102]
使用EasyRecyclerView  4.2版本在自定义dialog中  EasyRecyclerView用九宫格  dialog不会窗口化  高度直接充满屏幕      更换会4.0.2没有此问题

**Comment by Jude95** [comment]
什么是不会窗口化？如果是在dialog中，你应该手动设置固定高度吧？

**Comment by star-andy** [comment]
如果不想手动设定高度呢    之前4.0.2不需要设置固定高度值的

**Comment by star-andy** [comment]
`
<?xml version="1.0" encoding="utf-8"?>
<com.zhy.autolayout.AutoRelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="wrap_content"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_height="wrap_content">

```
<com.jude.easyrecyclerview.EasyRecyclerView
    android:id="@+id/dialog_color_view"
    android:layout_width="wrap_content"
    app:recyclerPadding="50px"
    android:layout_height="wrap_content"/>
```

</com.zhy.autolayout.AutoRelativeLayout>
`

**Comment by Jude95** [comment]
你使用了loadmore，nomore之类的功能了吗？
为什么不想手动设定高度？以前的高度是多少？
呃~在我的经验中。dialog中的View都要设置高度，或者给dialog设置高度。。虽然我还不清楚什么改动导致了这2个版本的区别。不过我觉得现在这样的逻辑也没有错。

**Comment by Jude95** [comment]
截张图更好。

**Comment by star-andy** [comment]
截图上传不上来  如果方便能加个QQ吗？

**Comment by Jude95** [comment]
Resolved
