### ISSUE TITLE
Adding different footer views based on a logic

### ISSUE THREAD

**Issue by rakesh1988** [Jude95/EasyRecyclerView#103]
Hi Jude,
Firstly thank you for the library. It is really helpful. I would like to know if it is possible to show different footers based on user action or a business logic.
For example, I would like to show different footer when 
- data is loading (show progressbar)
- error when fetching data from network (show a reload button)
- show end of data (show textview mentioning no more data)

Is it possible to display these based on business logic?

**Comment by Jude95** [comment]
Is this what you want?
![image](https://cloud.githubusercontent.com/assets/7901171/18907227/69888186-859d-11e6-86cb-415a73c8d494.png)
Forgive my poor English...
I provide the setting of the loading,error,end view.and use a common logic.In most situation.this logic works well.

For detail you can see this https://github.com/Jude95/EasyRecyclerView/blob/master/easyrecyclerview/src/main/java/com/jude/easyrecyclerview/adapter/DefaultEventDelegate.java
