### ISSUE TITLE
RecyclerArrayAdapter的addHeader方法错误导致定位出现问题

### ISSUE THREAD

**Issue by qiaoyj** [Jude95/EasyRecyclerView#105]
RecyclerArrayAdapter  第181行应改成 notifyItemInserted(headers.size()-1) ，否则会出现添加多个header后，当 header的总高度大于屏幕高度时出现定位到最后一个header开始位置的问题

public void addHeader(ItemView view){
        if (view==null)throw new NullPointerException("ItemView can't be null");
        headers.add(view);
//        notifyItemInserted(footers.size()-1);
        notifyItemInserted(headers.size()-1);
    }

**Comment by Jude95** [comment]
大意了，感谢指出。
