### ISSUE TITLE
没有fastScrollEnabled属性  

### ISSUE THREAD

**Issue by ghost** [Jude95/EasyRecyclerView#106]
怎么没有类似listview的快速滑动呢  
android:fastScrollEnabled="true"
我的数据都很多。

**Comment by fengzhous** [comment]
试试app:fastScrollEnabled="true"

**Comment by ghost** [comment]
试了，编译直接报错，说没有这个属性，因为你这个框架不是继承原生的RecyclerView  但是我们又必须要这个

**Comment by fengzhous** [comment]
@Jude95 确实没有这个属性，问问作者

**Comment by Jude95** [comment]
抱歉最近事太多，
RecyclerView真的有fastScrollEnabled这个属性吗...
