### ISSUE TITLE
关于SwipeRefreshLayout

### ISSUE THREAD

**Issue by paulyung541** [Jude95/EasyRecyclerView#107]
请问项目里面的SwipeRefreshLayout是否是对v4包那个SwipeRefreshLayout作了一些删减，我如果替换成v4包的SwipeRefreshLayout是否有影响？

**Comment by Jude95** [comment]
对他的layout部门做了修改，使其支持布局多个子View。并且修改手势处理部分，使其支持是否拦截手势的设置。你替换是有什么需求吗？
