### ISSUE TITLE
 setMore无法执行

### ISSUE THREAD

**Issue by FortuneDream** [Jude95/EasyRecyclerView#108]
往下滑动的时候，setMore的方法无法执行
跟源代码几乎是一模一样，但是我用的是fragment
//        adapter.setMore(R.layout.view_more, new RecyclerArrayAdapter.OnLoadMoreListener() {
//            @Override
//            public void onLoadMore() {
//
//                Log.i("EasyRecyclerView","onLoadMore");
//                handler.postDelayed(new Runnable() {
//                    @Override
//                    public void run() {
//
//                        Song song=new Song();
//                        song.setName("1");
//                        adapter.add(song);
//                    }
//                }, 2000);
//
//            }
//        });
还有这个方法已经不推荐使用了，新方法的两个回调方法是什么意思呢？

**Comment by Jude95** [comment]
Resolved
