### ISSUE TITLE
recyclerView.getSwipeToRefresh().setRefreshing(true) 没作用？

### ISSUE THREAD

**Issue by reaper12** [Jude95/EasyRecyclerView#11]
如题 调用这个方法没有作用 ,不会触发onRefresh事件，我是在recyclerView.setRefreshListener之后调用的

**Comment by Jude95** [comment]
呃~这原本是PullToRefreshLayout的BUG。不过我还是解决了吧，顺便加一个API。看看新版本  
`recyclerView.setRefreshing(true)`就好。

**Comment by reaper12** [comment]
新版本里setRefreshing也没触发onRefresh事件  我看您的例子里虽然调用了setRefreshing  但实际是最后手动调用了onRefresh方法

**Comment by Jude95** [comment]
满足你了。。看最新版。
