### ISSUE TITLE
加载更多策略是不是太草率了

### ISSUE THREAD

**Issue by finch001** [Jude95/EasyRecyclerView#110]
如果我分页查找，此时删除数据，当数据删除到不满一个屏幕。此时自动回调加载更多方法是否显得很不合理？
当数据没有铺满整个屏幕并且用户手动向上滑动才触发加载更多的回调会不会更好点

**Comment by ikkyu0319** [comment]
+1

**Comment by Jude95** [comment]
#28 
是我向你请求加载更多，不是向用户请求。加不加载是你决定的。
因为场景有很多，需求也各不相同。所以我只做了最基础的逻辑，你的需求可以自己加几行代码实现。
相不相信我改成你说这样，会有更多的issue问怎么判断满没满一屏，怎样在不满一屏自动加载更多。
