### ISSUE TITLE
easyrecyclerview（1）嵌套了easyrecyclerview（2）导致easyrecyclerview（2）向下滑动失效

### ISSUE THREAD

**Issue by huwencheng** [Jude95/EasyRecyclerView#112]
![2 lgec_i_3 8_m zpv 3a](https://cloud.githubusercontent.com/assets/8435177/19302788/5496d3c6-9098-11e6-9382-62927c26ee1a.png)

**Comment by Jude95** [comment]
请不要这样使用。请使用GridLayoutManager。或者将2作为一个item。或者横向的recyclerview。
