### ISSUE TITLE
当绑定数据的时候，怎么获取当前的position

### ISSUE THREAD

**Issue by tx123456** [Jude95/EasyRecyclerView#113]
我想在viewholder里面写一个接口，需要获取当前position,这个怎么获取

**Comment by ikkyu0319** [comment]
+10086

**Comment by ikkyu0319** [comment]
源码 是 这样写的                     

mItemClickListener.onItemClick(viewHolder.getAdapterPosition()-headers.size());

比如我的Item 里有其它的事件，也需要position 标识~

**Comment by ikkyu0319** [comment]
楼主的 click接口能否这样呢
    void onViewClick(int position, View view, T t);

实用价值更高一点

**Comment by ikkyu0319** [comment]
@Jude95 help

**Comment by Jude95** [comment]
@tx123456 你是第一个提这个需求的，很合理，满足你。
4.2.3新增`getDataPosition()`,`getOwnerAdapter()`，`getOwnerRecyclerView()`试试有没有bug...
至于@ikkyu0319 说的onViewClick里新增的2个参数。。我的考虑是。
data：你可以方便的用adapter通过position获取到data。而我要提供给你也只能是通过这种方式...所以按需获取，没必要提供。
view：极其不建议直接修改View。因为你直接修改了View，View被recycle后，就又恢复了。你的修改会丢失。正确方式应该是更新adapter的数据。所以没有提供View。

**Comment by ikkyu0319** [comment]
根据position取这个肯定可以，但是如果多类型的时候，再这样取就比较麻烦，没有用泛型直接带出来方便，灵活~
