### ISSUE TITLE
在onItemClick回调方法里面怎么得到当前传入的position位置的itemView

### ISSUE THREAD

**Issue by yushilong** [Jude95/EasyRecyclerView#116]
findViewHolderForAdapterPosition
findViewHolderForItemId
findViewHolderForLayoutPosition
这三个方法试了都不行
试过不减去adapter.getHeaderCount()和减去adapter.getHeaderCount()也不行，望告知，非常感谢！

**Comment by Jude95** [comment]
...为什么要获取itemView。我觉得这个需求不正常，非常不建议RecyclerView直接操作itemview。所以为了不误导使用者....我没有直接支持。
建议直接通过position修改数据,再notifydatasetchange。在viewholder里修改itemview。

不过，如果你执意要获取，这样写没有问题。

```
    adapter.setOnItemClickListener(new RecyclerArrayAdapter.OnItemClickListener() {
        @Override
        public void onItemClick(int position) {
            recyclerView.getRecyclerView().findViewHolderForAdapterPosition(position+adapter.getHeaderCount()).itemView.setBackgroundColor(Color.GRAY);
        }
    });
```

**Comment by yushilong** [comment]
嗯，我的需求其实是这样的，我是想点击itemview，然后获取到里面的imageview控件，然后实现图片的过渡效果。

**Comment by lumina0o0** [comment]
其实我也遇到了这个问题，我需要在列表页操作itemview里面的一个textview，实现他变大的效果，把之前没有的内容加进去，还要在列表页实现支付（可以理解为分答类似的需求），真是写的我要死了

**Comment by lumina0o0** [comment]
关于支付我有想过在activity中实现，hodler使用eventbus进行消息传递，但是我同一个hodler在三个以上页面复用了，所以用eventbus传消息似乎也不能实现，只能通过recycle来监听itemview，也许是我没想到更好的方法吧

**Comment by lumina0o0** [comment]
再补充一点，就是一个itemview里面不止一个控件需要点击事件，而有些控件又需要和recycleview所在页面交互，越说越复杂了。。。。

**Comment by yushilong** [comment]
嗯，作者已经给出了解决方案，已试验过，可以的。

**Comment by lumina0o0** [comment]
我们需求不太一样，不过这个问题可以关闭了，我正在想让产品改流程。。。。
