### ISSUE TITLE
数据不满一屏的时候底部依然会出现加载更多

### ISSUE THREAD

**Issue by reaper12** [Jude95/EasyRecyclerView#12]
数据不满一屏的时候底部依然会出现加载更多

**Comment by Jude95** [comment]
应该说添加了数据后。你没有手动停止加载更多(包括添加添加空数据)。都会出现加载更多。没有什么不合理的吧？

**Comment by reaper12** [comment]
现在的步骤是这样的 控件添加了下拉刷新和加载更多，一进来的时候调用下拉加载，如果加载的数据不满一屏的话，会自动去调用加载更多的方法，如果没有手动在加载更多里停止的话，会不停的一直调用。及时手动调用了停止的方法，但至少也会调用一次加载更多,而且调用了stopMore之后就再也没有加载更多了

**Comment by Jude95** [comment]
流程一般是：一进来的时候调用下拉加载，不满一屏，然后会马上调用加载更多。然后添加空数据(因为没数据，没有加空数据的机制也可以手动停止)。然后就显示没有更多（如果设置了的话，没设就是空白）。

对于`不停的一直调用`表示怀疑，如果你每次都加入了数据，那证明加载更多是正确运行了。如果加入的空数据就会停止。

对于及时手动调用了停止的方法，但至少也会调用一次加载更多。这个问题我测试并不存在。你在添加数据过后立即停止的？

就算你没有停止而多加载一次也没什么影响吧，不然如果是本来这一页本来就10条，而10条就是没有占满屏幕就永远没有机会加载第二页了。

**Comment by reaper12** [comment]
您说的这种情况是有可能出现，但大多情况下是比如一页10条可以占满屏，但我的数据就只有5条，如果再去执行一次加载更多的话，会有多余的网络请求操作，目前我的解决办法就只能判断在加载更多里去判断是否够一页的数据，够了的话再去进行网络操作，希望能有更好的解决办法吧

**Comment by Jude95** [comment]
。。下拉刷新数据添加进去过后，你判断没有更多了就立即停止
![image](https://cloud.githubusercontent.com/assets/7901171/12262242/b3101f20-b961-11e5-85d9-6138be716500.png)
