### ISSUE TITLE
滑动到底部加载更多问题

### ISSUE THREAD

**Issue by guoyoujin** [Jude95/EasyRecyclerView#121]
发现滑动到底部显示加载失败之后，不管如何上拉，都不能收到`onLoadMore`回调，找了下源码，没发现你在哪判断滑动到底部加载更多的判断，能否告知判断滑动到底部的代码

**Comment by lumina0o0** [comment]
没看懂你说的上拉，easy这个控件是不支持回弹的，所以你加载失败之后是无法继续上拉的，加载失败后应该在seterror里面进行处理,有onerrorshow，也有onerrorclick，建议好好看demo，我觉得demo写的还是很清楚的

**Comment by guoyoujin** [comment]
我就想知道你是在哪里判断加载更多的，看了下代码没找到

**Comment by lumina0o0** [comment]
onmorelistener
具体代码是
adapter.setMore(R.layout.view_more, this);
这些demo里面都有

**Comment by guoyoujin** [comment]
额，你没看懂我问的问题，我问的是在哪里判断加载更多，不是在哪监听

**Comment by lumina0o0** [comment]
所以你要看源码而不是要用是吧

**Comment by guoyoujin** [comment]
对啊，我就想知道她是如何判断在什么时候执行刷新回调事件的

**Comment by lumina0o0** [comment]
listview里面的下拉我写过，通过判断当前页面里面item的数量，和第一个item的position，还有item的总量来判断是不是要加载，虽然这里面的源码我没看，但是原理应该差不多

**Comment by lumina0o0** [comment]
你想做下拉刷新应该去google develop看源码，而不是来github看别人写的库里面的源码啊

**Comment by guoyoujin** [comment]
额，我只是想在他设置加载更多的时候干点事情。

**Comment by lumina0o0** [comment]
加载更多的时候就是setmore啊，在哪个方法里面就可以了，不看源码也能知道吧。。。。不知道为什么，觉得好累

**Comment by lqjymt** [comment]
setMore 在adapter.addAll()之后就不能上拉加载，setMore()在adapter.addAll()之前就能上拉加载。this is a problem,我也是不能回调到loadmore(),对比demo调试后才发现的。
