### ISSUE TITLE
刷新的时候如果没有数据变动就会乱跳

### ISSUE THREAD

**Issue by w0080626** [Jude95/EasyRecyclerView#122]
刷新的时候 如果是直接adapter.clear再adapter.addAll()这样的话如果没有新数据的话就会数据顺序乱跳。如果在addAll后自己手动notifyDataChange的话就不会了。

**Comment by Jude95** [comment]
。。没能复现，能发一张gif。或者把demo改一下使其出bug？

**Comment by xiejiajin** [comment]
为什么加载更多时会闪屏呢？
下面是加载更多的方法还有录屏
`public void updateView(List<NavTwoInfo.ObjsBean> entityList){
        if (entityList == null || entityList.size() == 0){
            easyRecyclerView.setRefreshing(false);
            mAdapter.stopMore();
            return;
        }
        ticketEntityList.addAll(entityList);
        mAdapter.addAll(entityList);
        mAdapter.notifyDataSetChanged();

```
    mAdapter.pauseMore();
}`
```

http://www.17sysj.com/video/lpds_3d2235278609a
