### ISSUE TITLE
当有添加Headview的时候 如果显示showEmpty headview 也消失了

### ISSUE THREAD

**Issue by wushange** [Jude95/EasyRecyclerView#123]
当有添加Headview的时候 显示showEmpty headview 也消失了 可不可以显示empty的时候保留headview

**Comment by Jude95** [comment]
手动想show谁就show谁。我只默认提供最常见逻辑。

**Comment by wushange** [comment]
我知道啊 但是showEmpty的时候  之前添加的headerview就没了

**Comment by Jude95** [comment]
因为...EmptyView和RecyclerView是平级的。。只有替换关系。
你可以不使用EmptyView自己写一个EmptyFooter随意加/删。

**Comment by wushange** [comment]
哦哦 谢谢
