### ISSUE TITLE
在adapter中使用glide加载本地图片，加载9张只会渲染出来三张

### ISSUE THREAD

**Issue by star-andy** [Jude95/EasyRecyclerView#124]
在adapter中使用glide加载本地图片，加载9张只会渲染出来三张，但是数据源里面是9张
![image](https://cloud.githubusercontent.com/assets/15726024/19919650/1fad0144-a10f-11e6-980c-5b42cd67787d.png)
![image](https://cloud.githubusercontent.com/assets/15726024/19919661/313cfa22-a10f-11e6-8b02-9cf0ebdbba8f.png)

**Comment by Jude95** [comment]
= =.难道因为你用了这个库，我就要为你解决你项目中的所有问题。

**Comment by star-andy** [comment]
额  我只是不知道是不是因为重用引起的问题。。。。。
