### ISSUE TITLE
库中集成的SwipeRefreshLayout的下拉刷新圆圈的颜色怎么设置？

### ISSUE THREAD

**Issue by guiying712** [Jude95/EasyRecyclerView#125]
库中集成的SwipeRefreshLayout的下拉刷新圆圈的颜色怎么设置？

**Comment by Jude95** [comment]
easyrecyclerview. setRefreshingColor

**Comment by protectedMan** [comment]
like this ` erv_car.setRefreshingColorResources(R.color.green);`
