### ISSUE TITLE
在执行onRefresh 的时候  Progress不显示

### ISSUE THREAD

**Issue by ggchxx** [Jude95/EasyRecyclerView#13]
//初始化adapter
        mAdapter = new MessageOutboxListAdapter(getThisContext());
        mList.setAdapterWithProgress(mAdapter);
        mAdapter.setMore(R.layout.recyclerview_item_more, this);
代码如上，在执行onRefresh 的时候  Progress不显示呢？

**Comment by Jude95** [comment]
我试了试。我猜有2个原因。
1.你没有setProgressView()..没设置就不会显示(xml与代码里设置均可)，没有默认View。
2.你setAdapterWithProgress过后再setMore就会失效。
原因2确实是我设计的不合理。3.3.3版本已经修改。
其实setAdapterWithProgress就等于setAdapter过后，调用showProgress....

**Comment by ggchxx** [comment]
OK可以了哈，关闭了
