### ISSUE TITLE
为什么加载更多时会闪屏呢？

### ISSUE THREAD

**Issue by xiejiajin** [Jude95/EasyRecyclerView#130]
下面是加载更多的方法还有录屏
`public void updateView(List entityList){
if (entityList == null || entityList.size() == 0){
easyRecyclerView.setRefreshing(false);
mAdapter.stopMore();
return;
}
ticketEntityList.addAll(entityList);
mAdapter.addAll(entityList);
mAdapter.notifyDataSetChanged();

    mAdapter.pauseMore();
}`
http://www.17sysj.com/video/lpds_3d2235278609a

**Comment by xiejiajin** [comment]
我用的是4.0.6版本

**Comment by Jude95** [comment]
不需要`mAdapter.notifyDataSetChanged();`
