### ISSUE TITLE
希望在RecyclerArrayAdapter中添加refresh及update方法

### ISSUE THREAD

**Issue by sanousun** [Jude95/EasyRecyclerView#132]

**Comment by Jude95** [comment]
...你不觉得你应该解释一下2个方法的作用吗

**Comment by sanousun** [comment]
。。好吧，refresh就是刷新全部列表，先clear在addAll，update就是刷新局部列表，先remove在add

**Comment by Jude95** [comment]
不好意思忘了回复.
关于refresh。我不觉得2行代码与1行代码有太大差别。
关于update。可以有不过先remove在add太折腾。直接notifyItemChanged()
应该今天更新。

**Comment by sanousun** [comment]
棒
