### ISSUE TITLE
希望能在点击监听返回里面加入itemView

### ISSUE THREAD

**Issue by ziktang** [Jude95/EasyRecyclerView#133]
有时需要更新item的ui，比如背景啊什么的，，就只能在viewholder里面设置监听了，，如果能将itemView在监听方法中放出来就好了

**Comment by Jude95** [comment]
Item的效果请在ViewHolder内部解决。与数据相关的UI变化，请修改数据再notify。直接操作可回收的View不是优秀的设计。
