### ISSUE TITLE
No animation on item removal

### ISSUE THREAD

**Issue by IRMobydick** [Jude95/EasyRecyclerView#135]
Hi there,
I'm using `adapter.remove()` to remove item from list, Both method which by `position` and `object` does not animate rest items to fill the gap! instead the item remove without animation!

How can bring the animation back?
thanks :)

**Comment by Jude95** [comment]
use `easyrecyclerview.setItemAnimator(new DefaultItemAnimator())` to add animator.I removed the default animator.

**Comment by IRMobydick** [comment]
nice 👍

**Comment by IRMobydick** [comment]
Hi there, I'm using `StaggeredGridLayoutMnager` with `SpaceDecoration`, When user delete an item from adapter, `SpaceDecoration` has weird behave and space between items set wrongly.

How can overcome it?
