### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:8).state:8  is occur

### ISSUE THREAD

**Issue by lqjymt** [Jude95/EasyRecyclerView#138]
when i  use rv.setItemAnimator(new DefaultItemAnimator());  java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:8).state:8  is occur

**Comment by Jude95** [comment]
can you paste the complete exception stack log and your code?
