### ISSUE TITLE
material design问题

### ISSUE THREAD

**Issue by 1247934711** [Jude95/EasyRecyclerView#139]
现在很多app都有列表滑动时，列表上面布局可以隐藏的效果。这种效果就是官方提供的material design。问题就在这，当我把作者自定义控件EasyRecycleView加入CoordinatorLayout内使用的时候，本身列表是没有什么问题，但是加载页面，错误页面上下方向不居中，作者能解决这个问题吗？
下面是我的主布局，作者可以看下（加载页面布局、错误页面布局作者随意加就行了，代码贴多了反而不清楚）。

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <RelativeLayout
        android:id="@+id/rl_head"
        style="@style/title_bar_style_home"
        android:fitsSystemWindows="true">

        <TextView
            android:id="@+id/home_top_title_tv"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:padding="10dp"
            android:text="修理厂客户端"
            android:textColor="@color/white"
            android:textSize="20sp"
            android:textStyle="bold" />

        <TextView
            android:id="@+id/rankings_tv"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignBottom="@id/home_top_title_tv"
            android:layout_alignParentLeft="true"
            android:layout_centerVertical="true"
            android:clickable="true"
            android:drawableLeft="@drawable/home_top_star"
            android:padding="10dp"
            android:text="光荣榜"
            android:textColor="@color/white"
            android:textSize="14sp" />
    </RelativeLayout>

    <android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <android.support.v7.widget.Toolbar
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:background="@color/themcolor"
                app:layout_scrollFlags="scroll|enterAlways" />

            <RelativeLayout
                android:id="@+id/rl_income"
                android:layout_width="match_parent"
                android:layout_height="160dp"
                android:layout_below="@id/rl_head"
                android:background="@color/themcolor"
                android:padding="10dp"
                app:layout_scrollFlags="scroll|enterAlways">

                <TextView
                    android:id="@+id/tv_title"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:text="今日收入（元）"
                    android:textColor="@color/white"
                    android:textSize="18sp" />

                <TextView
                    android:id="@+id/tv_price"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/tv_title"
                    android:layout_centerInParent="true"
                    android:layout_marginTop="30dp"
                    android:text="520.00"
                    android:textColor="@color/white"
                    android:textSize="50sp"
                    android:textStyle="bold" />

                <ImageView
                    android:id="@+id/home_top_arrow"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignParentRight="true"
                    android:layout_centerVertical="true"
                    android:src="@drawable/home_top_arrow" />

            </RelativeLayout>

        </android.support.design.widget.AppBarLayout>

        <com.jude.easyrecyclerview.EasyRecyclerView
            android:id="@+id/erv_offer"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            app:layout_empty="@layout/layout_empty_pager"
            app:layout_error="@layout/layout_load_error_pager"
            app:layout_progress="@layout/layout_loading_pager" />

    </android.support.design.widget.CoordinatorLayout>

</LinearLayout>

**Comment by Jude95** [comment]
能否放截图以说明问题？

**Comment by 1247934711** [comment]
![image](https://cloud.githubusercontent.com/assets/23330113/21382789/7160101c-c79d-11e6-9b47-d1adf835313b.png)
![image](https://cloud.githubusercontent.com/assets/23330113/21382934/2d9ef220-c79e-11e6-9683-7dc6069e98d4.png)

**Comment by 1247934711** [comment]
## layout_loading_pager.xml布局：
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:gravity="center_horizontal"
        android:orientation="vertical">
        <ProgressBar
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:text="拼命加载中..."
            android:textColor="@color/black"
            android:textSize="20sp"/>
    </LinearLayout>
</RelativeLayout>
## layout_load_error_pager.xml布局：
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:src="@drawable/list_load_error" />
</RelativeLayout>

**Comment by 1247934711** [comment]
### loading布局：
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:gravity="center_horizontal"
        android:orientation="vertical">

        <ProgressBar
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:text="拼命加载中..."
            android:textColor="@color/black"
            android:textSize="20sp"/>

    </LinearLayout>


</RelativeLayout>`

### error布局：
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:src="@drawable/list_load_error" />

</RelativeLayout>`

**Comment by 1247934711** [comment]
粘贴上面两个布局代码的时候不知道为什么根布局RelativeLayout不显示，所以这里说明一下，RelativeLayout就加了两个属性，分别为宽和高，都是match_parent。

**Comment by Jude95** [comment]
这与本库无关，CoordinatorLayout是将子View以自己的大小measure layout，然后AppBarLayout 的Behavior将目标View按依赖关系移动位置。整个EasyRecyclerview都下移了，图案当然会不相对屏幕居中。这个库没有办法也不应该解决此类问题。建议你直接将图片位置上移。
