### ISSUE TITLE
build.gradle编码

### ISSUE THREAD

**Issue by CoderKontar** [Jude95/EasyRecyclerView#14]
大兄弟，build.gradle啥编码？全是乱码

**Comment by Jude95** [comment]
utf-8....

**Comment by CoderKontar** [comment]
确定？其他都没事儿，就easyrecyclerview目录下的build.gradle乱码。。。

**Comment by Jude95** [comment]
确定。＝ ＝也只有你出了这个问题

**Comment by zhengxiaochuan** [comment]
就是easyrecyclerview这个moudle下的build.gradle乱码，android studio显示的编码时utf-8啊，你这个文件是有问题的

**Comment by Jude95** [comment]
。原来是说Jcenter上传的配置的注释。好吧，一直没在意。。与库无关。。。
