### ISSUE TITLE
RecyclerArrayAdapter380行， 插入刷新错误，不应该+1

### ISSUE THREAD

**Issue by qiaoyj** [Jude95/EasyRecyclerView#141]
public void insert(T object, int index) {
        synchronized (mLock) {
            mObjects.add(index, object);
        }
        if (mObserver!=null)mObserver.onItemRangeInserted(index,1);
        if (mNotifyOnChange) notifyItemInserted(headers.size()+index+1);
        log("insert notifyItemRangeInserted "+(headers.size()+index+1));
    }

**Comment by Jude95** [comment]
谢谢指出。确实不应该，好像是为了解决位置问题故意+1，在stackoverflow找的方案，记不大清了，我再仔细看看。

**Comment by Jude95** [comment]
insert确实没必要+1。但addAll不+1会出些问题，有footer的情况下，addAll也是insert。因为notifyItemInserted会保持屏幕当前item的位置，所以刷新时，footer会始终在底部，而item上移。
此问题已通过在EasyRecyclerView的Observer强行移动位置解决。+1的问题也已改正。
