### ISSUE TITLE
CollapsingToolbarLayout的滑动冲突

### ISSUE THREAD

**Issue by lumina0o0** [Jude95/EasyRecyclerView#142]
在写一个页面时，appbar中嵌套了一个collapsingtoolbar，需要实现列表滑倒顶端以后appbar先展开，然后才是easyrecycle的下拉刷新，但是在写的时候发现列表滑倒顶端以后，下拉事件被easyrecycleview抢先了，设置了behavior并没有用，把easyrecycleview替换之后，就没有问题

然后看了别的问题以后暂时的解决方法是不使用easyrecycle的下拉刷新，在easyrecycleview外面再套一个swiperefresh，在swipe里面设置behavior，冲突就解决了，看了下源码布局，easyrecycleview里面本身已经有一个swipe了，所以在外面再套一层肯定不太好，希望可以在源码里面加上这个属性

**Comment by lumina0o0** [comment]
忘了说了，已经更新了最新的4.2.6版本

**Comment by Jude95** [comment]
= =你这个场景我是无能为力的。硬要上的话，下拉刷新球也会在appbar下面。很丑。要我做也是在coodinatorlayout外面再套一个swiperefresh。

**Comment by lumina0o0** [comment]
想哭，不过我刷新球就是在appbar下面的

**Comment by Jude95** [comment]
...竟然想放下面。在屏幕中间下拉真的好吗。另外在外面再套一层没什么影响。不过是层级深一层。swiperefresh的布局也不复杂。

**Comment by lumina0o0** [comment]
我也是不懂我们ui，他还想抄知乎的修改密码的验证码设计，一个输入框就能搞定的验证码输入，他要我做六个，吵了一架，表示坚决不要这么做，最后才同意改设计，好气啊，设计上为什么不能为用户着想一点啊
