### ISSUE TITLE
希望可以增加分组功能

### ISSUE THREAD

**Issue by JamesP1949** [Jude95/EasyRecyclerView#144]
如题

**Comment by Jude95** [comment]
请详细描述一下...

**Comment by JamesP1949** [comment]
适用数据分组的情况 例如  #[分组1：item1 item2 item3... 分组2：item1 item2 item3... 分组3：item1 item2 item3
![screenshot_2016-12-12-19-49-38](https://cloud.githubusercontent.com/assets/20784704/21098522/943a016a-c0a4-11e6-8576-5884e2b7bd5b.png)
![screenshot_2016-12-12-19-51-21](https://cloud.githubusercontent.com/assets/20784704/21098530/9f850ad8-c0a4-11e6-8e1f-43e8cd03c93d.png)

**Comment by Jude95** [comment]
readme里 StickHeaderDecoration不能满足你？

**Comment by lumina0o0** [comment]
居然还有个StickHeaderDecoration，什么时候更新的么

**Comment by JamesP1949** [comment]
StickHeaderDecoration中的getHeaderId(int position)方法只能实现固定数量的item一个header 而实际运用中大多item数量是不固定的 另外项目中是不需要header悬浮的希望普通的分组实现 同时还有一个问题 使用StickHeaderDecoration方式还需要对获取的数据进行item和header的分离转换 并赋值给相应的适配器
希望能分离出来

**Comment by Jude95** [comment]
@JamesP1949 
1.= =并没有什么`只能实现固定数量的item`之类的限制。你再好好看看。
2.不需要header悬浮的情况，我以前一直都是用multiType实现的。这个东西就是为了解决你们悬浮的需求才加的。而不是说让你们分组全用这个。实现方式本来就很多。
3.item与header分离什么的。先不说你用multiType就不用分离。Adapter的设计本身不错吧，只是与你的业务设计不太符而已。很多场景根本没有header的数据只是构造UI，这个场景就非常合适，所以问题不在这，你转换一下也是应该的。

**Comment by JamesP1949** [comment]
回翻了示例 和library 已经搞清楚了 谢谢
