### ISSUE TITLE
使用GridLayoutManager的问题

### ISSUE THREAD

**Issue by yushilong** [Jude95/EasyRecyclerView#147]
我这样使用：
        GridLayoutManager gridLayoutManager = new GridLayoutManager(IGetContext(), 8);
        recyclerView.setLayoutManager(gridLayoutManager);
        SpaceDecoration itemDecoration = new SpaceDecoration(DeviceUtil.dp2px(6));
        recyclerView.addItemDecoration(itemDecoration);
然后看图片：
![device-2016-12-14-104511](https://cloud.githubusercontent.com/assets/5087094/21167878/9ff67550-c1ea-11e6-8d88-18017029338e.png)
然后你们有没有发现，两边的图片宽要小一点，仔细看哦。

**Comment by yushilong** [comment]
![8e202a28-01f3-4dd0-95ba-ba1235b1571d](https://cloud.githubusercontent.com/assets/5087094/21167996/8fffeaf4-c1eb-11e6-9020-bbdddeeade3d.png)
这个更明显

**Comment by Jude95** [comment]
确实有问题，建议先`setPaddingEdgeSide(false)`.我会尽快修复。

**Comment by Jude95** [comment]
4.3.3已修复

**Comment by yushilong** [comment]
谢谢您这么及时的修复，非常感谢！
