### ISSUE TITLE
EasyRecyclerView添加header,怎么在进入页面时就可以看到header

### ISSUE THREAD

**Issue by JakeyYe** [Jude95/EasyRecyclerView#150]
EasyRecyclerView添加RollPagerView作为header，但是进入页面header总是被顶到屏幕之外去了，一进去页面时看不到的，请问一下，该怎么设置才能在进入页面时就可以看到header？我看你的这个项目也没设置什么，就可以看到header啊，求解。

**Comment by Jude95** [comment]
你的header是后添加的吧。添加过后不会自动滚动到header所添加的位置，如果想到那里，请手动`scrollToPosition `

**Comment by JakeyYe** [comment]
我的`header`的添加顺序是和该例子一样的，是先`adapter.addAll()`之后再`adapter.addHeader()`的，但还是出现了上面的问题。还有就是`scrollToPosition`是`RecyclerView`的方法，只能在`RecyclerView`中的`Item`间滚动吧，问一下怎么手动滑动到`header`？

**Comment by Jude95** [comment]
请贴你的代码。重点不在谁先谁后，在于是不是同步调用。demo里是同步调用，所以没问题。
另外随时`easyrecyclerview.scrollToPosition(0);`即可到顶部。

**Comment by JakeyYe** [comment]
主要代码就是下面这些


	public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_zhi_hu, container, false);
        ButterKnife.bind(this, view);

        recyclerView.setAdapter(adapter = new ZhiHuAdapter(getActivity()));
        recyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));

        //加载最新数据
        getLatestData();//addAll,addHeader

        //加载更多
        adapter.setMore(R.layout.view_more, this);
         ..........

     }

     //加载最新的数据
    private void getLatestData() {
        ApiService apiManager = ServiceCreator.getInstance().createService();

        mSubscriptionLatest = apiManager.getLatestZhiHuStory()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Subscriber<latestZhiHuStory>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(Throwable e) {
                        ToastUtil.showToast(getActivity(),"网络连接失败！");
                        e.printStackTrace();
                    }

                    @Override
                    public void onNext(final latestZhiHuStory data) {

                        adapter.addAll(data.getStories());

                        //获取数据后直接在这里加载RollViewPager，数据为TopStoriesBean
                        adapter.addHeader(new RecyclerArrayAdapter.ItemView() {
                            @Override
                            public View onCreateView(ViewGroup parent) {
                      
                                RollPagerView header = new RollPagerView(getActivity());                     
                                header.setHintView(new ColorPointHintView(getActivity(), Color.WHITE, Color.GRAY));                           
                                header.setHintPadding(0, 0, 0, DisplayUtil.dip2px(getActivity(), 8f));
                                header.setPlayDelay(3000);
                                header.setLayoutParams(new                      RecyclerView.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
                                        DisplayUtil.dip2px(getActivity(), 200)));
                                header.setAdapter(new BannerAdapter(getActivity(), data.getTop_stories()));
                                return header;
                            }

                            @Override
                            public void onBindView(View headerView) {

                            }
                        });
                    }
                });
    }
我原来就是这么写的，header在一开始进去的界面就被顶到屏幕之外去了。我想了一下可能是在onNext()

中获取数据时是异步，但是打log发现数据是一次性获取的，所以还是不知道原因在那？希望作者能找到

原因解释一下。但是我通过在`onNext()`方法的最后面加上`easyrecyclerview.scrollToPosition(0)`解决了问

题，原来`easyrecyclerview.scrollToPosition(0)`是可以滑到header头部，但是

`easyrecyclerview.scrollToPosition(0)`这段代码的位置不知道为什么要放在onNext()方法中才起作用，我把

它放在`onCreateView()`，`onViewCreated()`,`onResume()`其中任何一个方法中都不起作用，不知道为什

么。这里先谢谢作者，感谢！

**Comment by Jude95** [comment]
你添加数据及Header都是在RecyclerView布局完成后才加的...我还没用这种姿势测过。可能RecyclerView布局完成后添加数据就会即时展示UI了把，所以header还是会顶到屏幕外。
不过这不重要。
添加了header后才出现的位置停在了中间，肯定应该在添加了header后调用`easyrecyclerview.scrollToPosition(0)`.  这个方法意思是...滑到顶部。

**Comment by JakeyYe** [comment]
好的，谢谢作者了：）。

**Comment by SiberiaDante** [comment]
请问楼上解决了吗，为什么我easyrecyclerview.scrollToPosition(0)后头布局还是背顶上去了呢
