### ISSUE TITLE
剥离刷新加载更多就好了

### ISSUE THREAD

**Issue by ruhaly** [Jude95/EasyRecyclerView#151]
什么时候可以剥离刷新加载更多就好了

**Comment by Jude95** [comment]
请详细描述？
另外EasyRecyclerView与RecyclerArrayAdapter之间并没有耦合关系。你可以单独用其中任何一个。混淆过后，也不存在方法数的问题。

**Comment by ruhaly** [comment]
有个问题哦，

![2222](https://cloud.githubusercontent.com/assets/4638754/21447741/7b93f558-c914-11e6-8f08-2ef26f6082df.png)

添加header之后 一开始设置 GridLayoutManager gridLayoutManager = new GridLayoutManager(getActivity(), 2);，后面无论怎么设置 全是这样，这事我重写的adapter     @Override
        public void onAttachedToRecyclerView(RecyclerView recyclerView) {
            super.onAttachedToRecyclerView(recyclerView);
            RecyclerView.LayoutManager layoutManager = recyclerView.getLayoutManager();
            if (layoutManager instanceof GridLayoutManager) {
                ((GridLayoutManager) layoutManager).setSpanSizeLookup(spanSizeLookup);
            }

        }
    }

    GridLayoutManager.SpanSizeLookup spanSizeLookup = new GridLayoutManager.SpanSizeLookup() {
        @Override
        public int getSpanSize(int position) {
            return 0 == position ? 1 : 1;
        }
    };
已经写死1了 还是不行

**Comment by Jude95** [comment]
= = 好好看demo与Readme。
![image](https://cloud.githubusercontent.com/assets/7901171/21469742/4863b92a-ca9f-11e6-9eea-58324cb492b3.png)

**Comment by ruhaly** [comment]
你的意思header要用recycleview？然后设置layout？

**Comment by ruhaly** [comment]
我看了demo的，好像没有使用gridlayout的

**Comment by Jude95** [comment]
就是指StaggeredGridActivity这部分。一样的。多加readme里写的那句话就行了。
```java
        GridLayoutManager gridLayoutManager = new GridLayoutManager(this,2);
        gridLayoutManager.setSpanSizeLookup(adapter.obtainGridSpanSizeLookUp(2));
        recyclerView.setLayoutManager(gridLayoutManager);
```

**Comment by ruhaly** [comment]
GridLayoutManager gridLayoutManager = new GridLayoutManager(getActivity(), 1);
//        LinearLayoutManager gridLayoutManager = new LinearLayoutManager(getActivity());
        latestGoodsRecV.setLayoutManager(gridLayoutManager);
        latestGoodsAdapter = new ServiceAdapter(getActivity());

已经加过了，错误我已经又提了个issue，请看一下，谢谢了
![image](https://cloud.githubusercontent.com/assets/4638754/21475637/e8835144-cb68-11e6-8a30-5089cf198a6a.png)

**Comment by Jude95** [comment]
你到底有多少列？
GridLayoutManager你说有1列。
setLookUp的时候又说有2列？
readme里说了参数是maxSpan

**Comment by ruhaly** [comment]
是两列的，但是如果设置了两列，就会出现上面那张图的效果，整个头部也变为一半了

**Comment by Jude95** [comment]
头部变为一半是因为你没有看readme添加我的lookup。
= =我已经给你们封装到极简了。稳定使用了1年多。这种需求还会有问题吗。

**Comment by ruhaly** [comment]
gridLayoutManager.setSpanSizeLookup(latestGoodsAdapter.obtainGridSpanSizeLookUp(2));
我的这一步，不就是你的lookup么？难道还有其他什么么

**Comment by ruhaly** [comment]
好像可以了，谢谢了
