### ISSUE TITLE
上拉加载更多功能失效

### ISSUE THREAD

**Issue by betroy** [Jude95/EasyRecyclerView#152]
首次加载数据调用insertAll方法后上拉加载更多功能失效

**Comment by Jude95** [comment]
insertAll 并不等于 addAll。
insertAll并不会触发数据加载的任何逻辑。因为很多需求是这样。
你有什么需求必须要用insertAll吗。
（= =现在好多问题已经不是代码bug，是不同场景的需求有逻辑冲突。）
