### ISSUE TITLE
gridLayoutManager.setSpanSizeLookup(latestGoodsAdapter.obtainGridSpanSizeLookUp(2));

### ISSUE THREAD

**Issue by ruhaly** [Jude95/EasyRecyclerView#153]
是这样子的么，好像出问题了
![image](https://cloud.githubusercontent.com/assets/4638754/21475236/22731b82-cb64-11e6-9832-235523ab1389.png)

**Comment by Jude95** [comment]
重复的issue。已在#151 回复。
