### ISSUE TITLE
能否添加自定义下拉刷新控件功能

### ISSUE THREAD

**Issue by kenynw** [Jude95/EasyRecyclerView#154]
能否添加自定义下拉刷新控件功能，有时候有些需要需要集成PullToRefresh这种下拉刷新的方式

**Comment by Jude95** [comment]
暂时未提供。很多需求是需要自定义下拉控件，而不只是使用`PullToRefresh `的交互方式。以后会考虑将下拉刷新做个抽象，以供拓展。毕竟改这个...很麻烦。

**Comment by kenynw** [comment]
我就是这个意思，最好是抽象出来
