### ISSUE TITLE
能不能加上公共变量

### ISSUE THREAD

**Issue by zoe-sky** [Jude95/EasyRecyclerView#155]
是这样，我实际使用的时候，除了需要加载的list外，还有一些公共数据需要同时传给adpater做更新。现在只能把公共数据整合到list的每一个item中。

**Comment by zoe-sky** [comment]
谢谢作者的辛苦付出

**Comment by Jude95** [comment]
没明白，什么是公共数据？

**Comment by star-andy** [comment]
@zoe-sky 写个方法传进去不行？
