### ISSUE TITLE
加载更多没显示nomore后向下滑一段在重新滑到底部 又重新请求了加载更多接口

### ISSUE THREAD

**Issue by star-andy** [Jude95/EasyRecyclerView#156]
不知道就是这样设计的还是我没使用明白.

我的预期是想出现nomore view后不点击就不会在重新请求了

**Comment by Jude95** [comment]
抱歉这麽久才回复，所有的请求都是你在回调里手动发起的。你应该查查你是否在正确的回调里进行请求。
