### ISSUE TITLE
刷新的时候 滚动问题

### ISSUE THREAD

**Issue by ruhaly** [Jude95/EasyRecyclerView#159]
在刷新的时候，同时滚动，这个滚动值貌似不对啊，请帮忙看看
![image](https://cloud.githubusercontent.com/assets/4638754/21669781/95fa3ff8-d349-11e6-8f2e-dcdf436a530b.png)

**Comment by ruhaly** [comment]
貌似是刷新之后，会自动滚动到开始的位置，可以设置还是之前的位置么

**Comment by Jude95** [comment]
这个现在不能，因为刷新实际是清空和添加2个步骤。
如果我再加API支持你这种模式，API会很难理解...这个需求并不常见吧。
如果你实在想要，可以修改源码。添加一个API，清空并添加新数据后直接`notifyItemRangeChanged`。
