### ISSUE TITLE
可以加个获取上一个数据得API吗？

### ISSUE THREAD

**Issue by twlk-jzy** [Jude95/EasyRecyclerView#163]
可以加个获取上一个数据得API吗？

**Comment by Developmc** [comment]
在adapter里边加上这个方法就行了，这个mObjects是RecyclerArrayAdapter内权限为protected的变量
/**获取数据源
     * @return
     */
    public List< T > getDatas(){
        return mObjects;
    }

**Comment by Jude95** [comment]
有`getAllData()`这个API

**Comment by twlk-jzy** [comment]
就是我想在  ViewHolder 的 setData里面  获取上一条数据   该怎么获取呢      还是可以在adapter里面  通过getAllData  获取到数据之后通过ViewHolder  传入进去呢   但是传入进去的时候  会不会造成数据混乱呢

**Comment by Jude95** [comment]
请解释什么是 上一条数据 。
