### ISSUE TITLE
分页加载错误的时候再重新加载，footview 会一直处于loading的状态

### ISSUE THREAD

**Issue by DomoXian** [Jude95/EasyRecyclerView#166]
情况描述：在有数据的情况下，分页加载错误，此时再重新加载，当加载到最后一页的时候footview会一直处于loading的状态，原因：DefaultEventDelegate类的addData方法中，当status的状态置为STATUS_ERROR，就不会再重新赋值了，所以导致footer.showNoMore()方法不能被调用了

**Comment by Jude95** [comment]
Thanks. 4.3.7已修复。看看还有没有bug...
