### ISSUE TITLE
加载更多时，显示加载更多view，但是没有触发加载更多的回调

### ISSUE THREAD

**Issue by star-andy** [Jude95/EasyRecyclerView#171]
![image](https://cloud.githubusercontent.com/assets/15726024/22729161/76c777fc-ee1c-11e6-808c-f12c593b1b62.png)

之前加载更多后只有两条，添加上以后  继续上拉加载更多，出现更多加载中view，但是没用回调加载更多监听。导致view无法消失。   只能向下滑动一段列表重新出发加载更多

**Comment by Jude95** [comment]
谢谢指出，4.3.8已修复。试试。

**Comment by star-andy** [comment]
已经ok
