### ISSUE TITLE
library中加入听云了吗? 我为什么老报错呢

### ISSUE THREAD

**Issue by caojunJackson** [Jude95/EasyRecyclerView#177]
dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
    }

**Comment by caojunJackson** [comment]
更新 4.4.0正常 , 谢谢

**Comment by Jude95** [comment]
没有
