### ISSUE TITLE
复用问题

### ISSUE THREAD

**Issue by Ludejin** [Jude95/EasyRecyclerView#18]
对于图片的展示或者viewholder使用GridView中图片也存在复用问题，OnBindViewHolder中处理下会更好

**Comment by Jude95** [comment]
没明白你说的复用是指什么？
OnBindViewHolder 等同于 viewholder 里的 setData().
并且我也提供了OnBindViewHolder供你特殊情况的复写。

**Comment by Ludejin** [comment]
就是图片会出现复用，图片显示的位置不对，本来是第一个item中的图片，显示到其他Item中去了。（复用混乱）

**Comment by Ludejin** [comment]
对了，我现在用的是setIsRecyclable(false);来解决这个问题，但是这样性能下降好恐怖，所以应该在RecyclerArrayAdapter中添加写处理来解决复用混乱的问题

**Comment by Jude95** [comment]
看了demo吗。用法一样吗。已经很多个大型项目使用了，并没有这样的问题，在显示逻辑上是recyclerview原生的逻辑，我并没有作修改。你可以贴下你的代码。

**Comment by NitroXenon** [comment]
@Ludejin 千萬不要用 `setIsRecyclable(false)` , 效能會降很大
其實這個是RecyclerView的問題，而不是這個庫的問題
我的做法是就算圖片不用加載，也應 `setImageDrawable(null);`
如果你用glide, 就 `Glide.clear(imageView)`

這是我的code

``` java
        if (!imgUrl.isEmpty()) {
            // 加載圖片
            Glide.with(imageView.getContext()).load(imgUrl).into(imageView);
        } else {
            // 圖片網址為空，清除imageView的Drawable
            Glide.clear(imageView);
            imageView.setImageDrawable(null);
        }
```

你可以試一下，希望對你有幫助!!

**Comment by Ludejin** [comment]
@NitroXenon 谢谢，根据你给的我试试，我用的并不是纯粹的imageView；

**Comment by Ludejin** [comment]
@Jude95 
这是我的viewholder：
`private MoreTextView mContent;
    private NoScrollGridView mImages;
    private TextView mSupport;
    private TextView mReads;
    private TextView mCollect;
    private ImageView mActionComment;

```
private CommentClickListener listener;

public CowSayViewHolder(ViewGroup parent, int res) {
    super(parent, res);
```

//        presenter = new CowSayPresenterImpl(this);

```
    mContent = $(R.id.tv_cow_say_content);
    mImages = $(R.id.item_cow_say_gridView);
    mSupport = $(R.id.item_cow_say_support);
    mReads = $(R.id.item_cow_say_read);
    mCollect = $(R.id.item_cow_say_collect);
    mActionComment = $(R.id.item_cow_say_action_comment);
}

@Override
public void setData(CowSayResBean.CowSayInfoEntity data) {
    super.setData(data);

    mSupport.setText(String.valueOf(data.getSupCount()));
    mReads.setText(String.valueOf(data.getReadCount()));
    mContent.setText(data.getContent());
    mCollect.setText(String.valueOf(data.getColCount()));

    mActionComment.setOnClickListener(this);

    if (data.getPictures().size() > 0 && data.getPictures() != null) {
        CowSayImageWithoutAddAdapter adapter = new CowSayImageWithoutAddAdapter(data.getPictures(),getContext());
        mImages.setAdapter(adapter);
    }
    setIsRecyclable(false);

}`
```

这是adapter：
`private CowSayViewHolder.CommentClickListener listener;

```
public CowSayInfoAdapter(Context context) {
    super(context);
}

@Override
public BaseViewHolder OnCreateViewHolder(ViewGroup parent, int viewType) {
    CowSayViewHolder viewHolder = new CowSayViewHolder(parent, R.layout.item_cow_say_info);
    viewHolder.setCommentListener(listener);
    return viewHolder;
}

public void setCommentListener(CowSayViewHolder.CommentClickListener listener){
    this.listener = listener;
}`
```

**Comment by Jude95** [comment]
CowSayImageWithoutAddAdapter 里面怎么写的。图片混乱应该就是是快速滑动下图片异步加载的问题。你要考虑回收过后，第二次加载的图片比第一次加载的图片先返回的情况。

**Comment by Ludejin** [comment]
@Jude95  这么说好像是这个道理，考虑不周啊，我先研究研究，不懂再问问你。谢谢哈！

**Comment by NitroXenon** [comment]
@Ludejin 看看這個 : http://www.zhihu.com/question/27818921

```
著作权归作者所有。
商业转载请联系作者获得授权，非商业转载请注明出处。
作者：张明云
链接：http://www.zhihu.com/question/27818921/answer/70279930
来源：知乎

使用Adapter的时候，如果你使用了ViewHolder做缓存，在getView的方法中无论这项的每个视图是否需要设置属性(比如TextView设置的属性可能为null，item的某一个按钮的背景为透明、某一项的颜色为透明等)，都需要为每一项的所有视图设置属性（textview的属性为空也需要设置setText("")，背景透明也需要设置），否则在滑动的过程中会出现内容的显示错乱。
```

**Comment by Ludejin** [comment]
@Jude95 我做的是类似朋友圈的功能，有一个自定义的MoreTextView实现收起和全文功能，还有一个NoScrollGridView（自动高度并不可滑动）实现图片展示，主要是这两个东西出现混乱情况；

**Comment by Ludejin** [comment]
@Jude95 仅仅是图片倒是没什么问题。

**Comment by Ludejin** [comment]
@Jude95 找到原因了，是GridView中adapter使用viewholder缓存造成的，现在好了。

**Comment by Ludejin** [comment]
@NitroXenon 谢谢，已经解决那个问题

**Comment by star-andy** [comment]
@Ludejin 你最后是怎么解决的呢？

**Comment by Ludejin** [comment]
@qinyang1018 好久了，那是上上个项目了吧，你说说你的问题看看

**Comment by star-andy** [comment]
已经解决了  item布局的问题，自适应会不显示   谢了

**Comment by chengzhijun0706** [comment]
![image](https://cloud.githubusercontent.com/assets/13751034/21476164/3d241880-cb70-11e6-8c46-ebd4f4a1cb94.png)
@Ludejin 我也是在做一个朋友圈的功能，有一个收起的自定义的view出现了这个问题，请问一下你是怎么解决的呢？

**Comment by Ludejin** [comment]
@chengzhijun0706 你试试是不是缓存的问题

**Comment by chengzhijun0706** [comment]
![image](https://cloud.githubusercontent.com/assets/13751034/21478494/daf41a0e-cb86-11e6-8ac3-8c1050517765.png)
@Ludejin 没有缓存，就是如果字出现三行以上才会出现全文和展开的字样，但是现在如果快速滑动，这个字样就会乱跑

**Comment by Jude95** [comment]
@chengzhijun0706  你得知道RecyclerView为什么叫Recycler....
ViewHolder是循环利用的。建议在setData里先将所有View状态初始化。或者你小心点补完所有的else。
