### ISSUE TITLE
横向的RecyclerView  loadMoreView显示不出来？

### ISSUE THREAD

**Issue by 244317809** [Jude95/EasyRecyclerView#19]
谢谢你提供一个这么好用的控件，在正常情况下这个控件简单易用，但是我试了一下在LayoutManager为HORIZONTAL时候loadMoreView显示不出来？是不是我的用法有问题？（通过addFooterView()可以添加显示出来， 但这样无法调用loadMoreListener）

**Comment by Jude95** [comment]
用的是LinearLayoutManager吗？我在把demo的下拉刷新示例改成HORIZONTAL测试没有问题。检查下你设置的MoreView的高度和宽度？

**Comment by 244317809** [comment]
你好，上面那个问题我解决了。现在遇到了一个新的问题，是关于LoadMore的，在加载出第一页内容后，全选把Item全部删掉，这个时候底部MoreView怎么没显示出来，loadMoreListener不再触发，就像移除了MoreView一样，困扰好几个小时了，可以帮我一下吗？谢谢！

**Comment by Jude95** [comment]
首先确认没有给EasyRecyclerView设置EmptyView
clean这个方法比较特殊，会初始化Adapter状态，所以会隐藏LoadMore。因为比起你这种需求。clean用来刷新要普遍的多。
你如果要清空还要保留loadmore。这其实不是清空。是删除所有。用下面的方式。

```
            adapter.setNotifyOnChange(false);
            int count = adapter.getCount();
            for (int i = 0; i < count; i++) {
                adapter.remove(0);
            }
            adapter.setNotifyOnChange(true);
            adapter.notifyDataSetChanged();
```

`adapter.setNotifyOnChange(false);`只是为了提高效率。一个一个删完的话就不会有clean的特殊处理。。
因为我也不了解你这个需求，我自己也没遇到这种需求。需要我给删除所有数据单独提供一个API吗？

**Comment by 244317809** [comment]
谢谢回复！！但我在ReadMe文件中找到了更好的解决办法，在`clean()`之后再执行一下`resumeMore()`方法，这样LoadMore又会有效了。这个框架很好用！
