### ISSUE TITLE
自定义adapter，未继承RecyclerArrayAdapter，没有触发 onLoadMore

### ISSUE THREAD

**Issue by c2545500** [Jude95/EasyRecyclerView#191]
自定义adapter，未继承RecyclerArrayAdapter，没有触发 onLoadMore
我想问  就是所有的adapter 都 必需继承你的 RecyclerArrayAdapter 吗？
在activity页面中能不能 像下拉刷新这种 recyclerView.setRefreshListener(this);   来设置加载更多事件

**Comment by lumina0o0** [comment]
implements RecyclerArrayAdapter.OnMoreListener,loadMore就是RecyclerArrayAdapter中的方法，建议多看源码

**Comment by Jude95** [comment]
@lumina0o0 thanks.
