### ISSUE TITLE
OnItemClick change affects other rows in the Recyclerview

### ISSUE THREAD

**Issue by bmbariah** [Jude95/EasyRecyclerView#194]
I am using your demo app and noticed that if I change the background color of any item in the view via OnItemClick, say to color red; Some other untouched views will also be changed.. 

To replicate this bug simply:

1. Add this code in your any activity

```java
 adapter.setOnItemClickListener(new RecyclerArrayAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(int position) {
                recyclerView.getRecyclerView().findViewHolderForAdapterPosition(position + adapter.getHeaderCount()).itemView.setBackgroundColor(Color.RED);
            }
        });
```
 
2. Add a margin to item_person.xml... To allow you to see the background change.
3. Load more data into DataProvider.java.. Try with at least 20 or 30 items

You'll notice that if you click on an item and it's background changes to RED then scroll further down, other rows will be RED even though they haven't been touched. This issue is replicated even with OnItemClick in ViewHolder.

Kindly assist...Thanks

**Comment by Jude95** [comment]
Do you know why RecyclerView called 'Recycler'?
You can repeat this in any RecyclerView.

I suggest you to save color state in data, 
and set the onclicklistener for itemview in viewholder to  change data's color state, 
and render the view at the beginning of setData.

**Comment by bmbariah** [comment]
Sorry ! Fixed this issue weeks ago but forgot to close it here.
