### ISSUE TITLE
如何动态的设置SpanCount

### ISSUE THREAD

**Issue by ruhaly** [Jude95/EasyRecyclerView#195]
现在只有用这个gridLayoutManager.setSpanSizeLookup(adapter.obtainGridSpanSizeLookUp(3));

这种方式可以用么？
   GridLayoutManager.SpanSizeLookup spanSizeLookup = new GridLayoutManager.SpanSizeLookup() {
        @Override
        public int getSpanSize(int position) {
            return menuList.get(position).getIconRes() != 0 ? 3 : 1;
        }
    };

**Comment by Jude95** [comment]
注意下header,footer和装饰就行了。你也可以参考obtainGridSpanSizeLookUp的实现
