### ISSUE TITLE
上拉加载bug

### ISSUE THREAD

**Issue by ouyuan2019** [Jude95/EasyRecyclerView#197]
没有更多数据了，onLoadMore还是会回调

**Comment by yurenmatou** [comment]
我也遇到了

**Comment by zhangchaoxu** [comment]
我也遇到了类似问题，请问你们是怎么解决的？

**Comment by Jude95** [comment]
我测试是没有问题的。
请详细描述问题，以及附上代码。
另外请不要随意贴bug标签，按照以往情况，这类问题几乎都是你们使用不当，可以先查找以前的issue。

**Comment by ouyuan2019** [comment]
@Jude95 你好，这个问题在demo上也有的。当界面已经加载到底部了，往上滑动一点距离，再滑动到底部时，会继续加载，onLoadMore状态也会变成加载状态

**Comment by Jude95** [comment]
@ozy20 那是我在onCreate加的设置，当没有更多被展示的时候，去加载更多。
loadmore，nomore，error 3种状态。都可以设置被展示/被点击事件。

**Comment by zhangchaoxu** [comment]
@Jude95 Thanks
确实是由于没有理解adapter.setNoMore(R.layout.view_nomore, onNoMoreListener)的OnNoMoreListener中设置了adapter.resumeMore()的作用引起的。

修改后的RefreshAndMoreActivity就不会引起误会了。

建议close this issue

**Comment by Jude95** [comment]
已修改

**Comment by yurenmatou** [comment]
RefreshAndMoreActivity 这个类只是修改了没有更多时回调为null，好像其他没变化，把数据控制三条，还是会连续加载更多，而且是自动触发的。

**Comment by Jude95** [comment]
@yurenmatou 如果你是说不满一屏会回调加载直到一屏。请看 #28
