### ISSUE TITLE
addHeader情况下无数据时，showEmpty()

### ISSUE THREAD

**Issue by Hi-Mike** [Jude95/EasyRecyclerView#20]
private void update() {
            log("update");
            if (recyclerView.getAdapter() instanceof RecyclerArrayAdapter) {
                if (((RecyclerArrayAdapter) recyclerView.getAdapter()).getCount() == 0){
                    log("no data:"+((hasProgress&&!isInitialized)?"show progress":"show empty"));
                    if (hasProgress&&!isInitialized)recyclerView.showProgress();
                    else recyclerView.showEmpty();
                } else{
                    log("has data");
                    recyclerView.showRecycler();
                }
            } else {
                if (recyclerView.getAdapter().getItemCount() == 0) {
                    log("no data:"+((hasProgress&&!isInitialized)?"show progress":"show empty"));
                    if (hasProgress&&!isInitialized)recyclerView.showProgress();
                    else recyclerView.showEmpty();
                } else{
                    log("has data");
                    recyclerView.showRecycler();
                }
            }
            isInitialized = true;//设置Adapter时会有一次onChange。忽略此次。
#         }

process情况下，getCount()=0， 未考虑header在无数据时也需要显示的场景，导致调用showEmpty()，设置是否需要在无数据时，显示header、footer？

**Comment by Jude95** [comment]
对。
有需要一直显示header／footer时，就不会设置EmptyView，ProgressView这些，它们就没有展示需求。
既然你设置了。就说明header／footer是不需要一直显示的。

你既需要header／footer一直显示，又设置了EmptyView，ProgressView这些。我默认是先照顾EmptyView，ProgressView这些的逻辑。你可以直接showRecycler()，showEmptyView()等主动控制这些逻辑。

**Comment by gzfgeh** [comment]
但是好多都是有Header，并且想显示EmptyView等的

**Comment by Jude95** [comment]
现版本并没有设计这几个View层叠显示。
要做也只能是层叠显示，EmptyView与Header的位置不会有相关。这样接受吗？

**Comment by gzfgeh** [comment]
我看了源码，感觉RecyclerView一直显示，并且布局改为
`
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <android.support.v7.widget.RecyclerView
            android:id="@android:id/list"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:scrollbars="vertical"
            android:clickable="true"/>
        <FrameLayout
            android:id="@+id/empty"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clickable="true" />
        <FrameLayout
            android:id="@+id/progress"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clickable="true" />

```
    <FrameLayout
        android:id="@+id/error"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clickable="true" />
</LinearLayout>`
```

估计就行了，我只是这样想的，不知道影响其他功能不

**Comment by gzfgeh** [comment]
不知道怎么粘贴xml好看，我这里在描述一下就是 把android.support.v7.widget.RecyclerView他的父布局改为LinearLayout，并且android.support.v7.widget.RecyclerView改为android:layout_height="wrap_content"就行了，并且RecyclerView一直显示，这样应该可以？

**Comment by Jude95** [comment]
= =。我觉得不太合适。你这么塞EmptyView。footer怎么想..与设计相悖。
EmptyView与ProgressView和ErrorView的处理方式也不同了。好难受。
视图层级加深还是用了weight的LinearLayout。消耗很大。为了1个不常用的功能，拖累所有开发者效率。

我觉得你可以直接addFooter加一个大小合适的EmptyView。控制add&remove。
或者欢迎fork做一个自己的版本。
