### ISSUE TITLE
为什么点击时候没有波浪纹效果呢？

### ISSUE THREAD

**Issue by fuxuemingzhu** [Jude95/EasyRecyclerView#22]
在ViewHold中 设置item.setonClickListener()没有波浪纹效果。用adapter.setonItemClick()也没有波浪纹效果，请问这个应该怎么设置出来呢？

**Comment by Jude95** [comment]
这个功能本来就不是recyclerView应该负责的吧。

给你itemview的xml布局最外层加上。
`android:foreground="?android:attr/selectableItemBackground"`
如果你的itemview没有点击事件，再加上`android:clickable="true"`

**Comment by JakeyYe** [comment]
@fuxuemingzhu 请教一下，我在itemView的最外层父布局里加上了android:foreground="?android:attr/selectableItemBackground"，或者再加上android:clickable="true"，也没有波纹效果，问一下，你是怎么写才有波纹效果的。
