### ISSUE TITLE
想给RecyclerView增加layout_behavior怎么做

### ISSUE THREAD

**Issue by kyleada** [Jude95/EasyRecyclerView#23]
感谢Jude95的作品。
因为需要和toolbar联动处理Toolbar的收缩变化，需要给RecylerView增加layout_behavior, 我尝试直接拷贝代码，在layout_progress_rv中增加,但layout_behavior是给CoordinatorLayout用的，编译会出错
请教使用EasyRecyclerView时怎么实现和CollapsingToolbarLayout的联动？
谢谢

**Comment by Jude95** [comment]
直接加`app:layout_behavior="@string/appbar_scrolling_view_behavior"`就可以了哟。
原理可以看看 我写的这篇[文章](http://www.jianshu.com/p/a506ee4afecb)
我也在demo中添加了在可收缩Toolbar的场景中的应用示例。可以更新看看。

**Comment by kyleada** [comment]
只能说太完美了，我能想到的需要封装的，这里都有了，多谢多谢。
