### ISSUE TITLE
如何取消滑动到边界时的阴影

### ISSUE THREAD

**Issue by yedajiang44** [Jude95/EasyRecyclerView#233]
如题

**Comment by ciscolxh** [comment]
在layout_progress_recyclerview布局下的RecyclerView控件改为
<android.support.v7.widget.RecyclerView
        android:id="@android:id/list"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="none"
        android:overScrollMode="never"
        android:clickable="true"/>

**Comment by yedajiang44** [comment]
三个月终于有人回了！哈哈哈！谢谢了！
