### ISSUE TITLE
非LinearLayoutManager的情况，对末尾的加载条集成不够好

### ISSUE THREAD

**Issue by trity1993** [Jude95/EasyRecyclerView#24]
![2016-03-22 5 52 21](https://cloud.githubusercontent.com/assets/10337957/13947719/0cabcf30-f057-11e5-8f16-44fee7034f18.png)

**Comment by Jude95** [comment]
在GridLayoutManager模式中需额外加一句

```
//用adapter去生成一个LookUp设置给LayoutManager，参数是列数。
 gridLayoutManager.setSpanSizeLookup(adapter.obtainGridSpanSizeLookUp(2));
```

**Comment by trity1993** [comment]
@Jude95 THX，直接看demo,而看README.md不够仔细
