### ISSUE TITLE
EasyRecyclerView databinding 会刷新所有的数据

### ISSUE THREAD

**Issue by cmlmonkey** [Jude95/EasyRecyclerView#25]
本人懒癌，觉得还是 android:visibility="@{userInfo.videostatus==1?View.VISIBLE:View.GONE}这样方便，特别一个item里面多个图标显示隐藏。notifyDataSetChanged会刷新所有的数据，导致上面加载的数据会闪，需要增加 新增／删除／更新对应的方法
        public final void notifyItemRangeChanged(int positionStart, int itemCount)
        public final void notifyItemRangeInserted(int positionStart, int itemCount)
        public final void notifyItemRangeRemoved(int positionStart, int itemCount)

**Comment by Jude95** [comment]
Adapter有如下方法。都可以正常使用，并不会刷新全部。

```
     * @see #notifyItemChanged(int)
     * @see #notifyItemInserted(int)
     * @see #notifyItemRemoved(int)
     * @see #notifyItemRangeChanged(int, int)
     * @see #notifyItemRangeInserted(int, int)
     * @see #notifyItemRangeRemoved(int, int)
```

**Comment by cmlmonkey** [comment]
mNotifyOnChange 设置 false，然后 notifyItemRangeInserted
好的，谢谢啦
