### ISSUE TITLE
不足一屏

### ISSUE THREAD

**Issue by ruhaly** [Jude95/EasyRecyclerView#28]
不足一屏时，能不显示下面的loading view么？

**Comment by Jude95** [comment]
不足一屏时，肯定要显示loading view。不然别人本来第一页就是没占满的就没有机会加载更多。
如果你不会去加载更多，干嘛要设置loading view。
就算你设置了loading view。你也可以在需要的时候stopMore()

**Comment by ruhaly** [comment]
不一定吧，这样要是数据就一条，我上来就是连续请求两次，本身刷新一次，然后又加载一次更多，不觉得有问题么？

**Comment by Jude95** [comment]
控件是无辜的，同一个场景，不同的需求，需要不同的处理，我只能默认满足最常见的需求。但肯定支持自己去干预处理以满足自己的需求。
你需要在本身刷新刷新的那次回调里检查数据是否只有这么多，然后去`stopMore()`。
分页的场景中，控件不可能知道你总数据有多少条。都需要你自己去查询并在添加最后一页(也许第一页就是最后一页)数据的时候去`stopMore()`或者`addAll(null)`。

**Comment by yurenmatou** [comment]
我觉得不合理呀，如果数据有三条，里面自动触发再次请求，访问网络然后解析到数据，这个时候进行逻辑判断，才知道要不要去加载更多，但是由于是自动触发的，那么时间上比我们人为调用stopMore要快，那么这个时候就算你停止了，一样会浪费不必要的请求。

**Comment by Jude95** [comment]
我不知道你有没有下一页，要不要加载更多。你知道，你可以在加载第一次的3条数据就后stop。你不stop，才继续回调你。但只是回调你，进不进行网络请求是你决定的，反正你不让我停我就不会停。

**Comment by yurenmatou** [comment]
恩恩，但是网络还是调用了，不是吗，所以能改进一下是最好的。虽然可以控制停止，但是时间上还是慢了

**Comment by Jude95** [comment]
是你调用的，你不调用不行？
我没明白你的想法。我写的业务从来就不会多调用。也没有慢什么。

**Comment by yurenmatou** [comment]
肯定会呀，你自己试试不满一屏的情况，看调用了多少次，如果是满一屏，你的逻辑是没错的。平时的业务是按page加载的，不管page_size 多少条，有就加载，没有就代表没有下一页。

**Comment by Jude95** [comment]
案例1：
业务设计：API{返回总页数，当前页数，本页数据列表(默认一页3条数据)}
场景：数据库只有3条数据。
首次onRefresh。添加3条数据，如果总页数 = 当前页数。stop。=>0次加载更多。

案例2：
业务设计：API{本页数据列表(默认一页3条数据)}
场景：数据库只有3条数据。
首次onRefresh。添加3条数据。此时控件不知道有没有下一页，回调你，
在回调里：
   你也不知道有没有下一页，你去再次网络请求，返回0条数据。stop =>1次加载更多。
   你知道没有下一页，不进行网络请求，stop=>0次加载更多。

哪里多了？
