### ISSUE TITLE
怎样设置EasyRecyclerView为横向的？

### ISSUE THREAD

**Issue by lzx1** [Jude95/EasyRecyclerView#30]
设置横向的是不是直接设置LinearLaoutManager的Orientation属性就可以了啊，但是会报空指针错？为什么

**Comment by lzx1** [comment]
是不是一个界面中不能用两个EasyRecyclerView？这个bug怎么解决啊

**Comment by Jude95** [comment]
= =..第一个问题，不会。不知道你是以怎样的姿势写的。
第二个问题，EasyRecyclerView就是个普通View。放多少个都没关系。说bug请详细。

**Comment by lzx1** [comment]
是这样 第一问题已经解决 是我的问题 第二个是我在一个界面中放置了两个横向的EasyRecyclerView但是我用的是同一个Adapter项目直接Crash掉了

**Comment by Jude95** [comment]
一个Adapter不能被多个RecyclerView同时使用....请new2个。

**Comment by lzx1** [comment]
好的 3q
