### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by lzx1** [Jude95/EasyRecyclerView#31]
有没有可以自定义刷新头部动画的刷新控件啊 推荐一个？

**Comment by Jude95** [comment]
这个库没有支持自定义。对于自定义刷新动画的库只知道这个[BGARefreshLayout](https://github.com/bingoogolapple/BGARefreshLayout-Android)也没用过

**Comment by captain-miao** [comment]
@lzx1 这个，巨完美：https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh
