### ISSUE TITLE
更新数据

### ISSUE THREAD

**Issue by ruhaly** [Jude95/EasyRecyclerView#33]
更新数据 必须调用 addAll(list)么？我直接更改list这个数据源的话，列表数量是不会变的，这事怎么回事，已经调用了notify了

**Comment by Jude95** [comment]
Adapter拥有自己所维持的List。你修改你所添加的List是没有用的。使用remove，clear，add，addAll。
当然你修改Item的话，notify是肯定有用的。

**Comment by ruhaly** [comment]
public void updateData(MomentListResult result, int type) {

```
        if (type == Constant.REFRESH) {
            this.list.clear();
            this.list.addAll(result.getDynamicList());
            clear();
            addAll(list);
        } else {
            this.list.addAll(result.getDynamicList());
            notifyDataSetChanged();
        }
    }
```

我现在这么写的，有什么更好的方式么

**Comment by Jude95** [comment]
没太明白你`list.clear()`与`clear();`的2次操作。
addAll过后没必要`notifyDataSetChanged`(除非你关了notify)。
应该没什么问题...

**Comment by ruhaly** [comment]
貌似有个问题，如果我设置了分割线 比如20dp，那么下拉刷新的view貌似距离上面也有20dp，这个咋办呢

**Comment by Jude95** [comment]
别用RecyclerView的分割线设置吧，直接在Item里画？

**Comment by ruhaly** [comment]
那不还是一样么，我item的  bottomMargin设置20dp的话，那最后一个不还是距离footer20dp么

**Comment by Jude95** [comment]
那你自己实现一个ItemDecoration。去根据item的位置绘画Divider。要注意Header／Footer的影响。
或者自己在item代码判断下是否为最后一个...
其实一般需求都是在item底部画一条分割线。所以最后一个item与加载更多的View之间存在一条分割线也很合理。
需要我自定义一个ItemDecoration来方便实现这些需求吗。

**Comment by Jude95** [comment]
试试库里新增的Decoration。抱歉Decoration的开发拖了这么久。
