### ISSUE TITLE
下拉刷新的时候 会闪过白屏一会再显示出来数据 

### ISSUE THREAD

**Issue by TigerChain** [Jude95/EasyRecyclerView#34]
下拉刷新 请求服务器回数据的时候会闪过白屏一小会再显示出来数据，这个如何修复呢

**Comment by Jude95** [comment]
并不会有白屏。他只是个RecyclerView...
是不是你自己在下拉时就clear。数据加载后才add导致的白屏。

**Comment by TigerChain** [comment]
谢谢了，你说对了，我改一下，呵呵
