### ISSUE TITLE
编辑列表

### ISSUE THREAD

**Issue by chaxin** [Jude95/EasyRecyclerView#35]
实现编辑列表功能好麻烦。朱大是用什么优雅的方式实现的。

**Comment by Jude95** [comment]
这个库并没有对列表编辑提供便捷方案。
也不知道你的具体需求，我个人在例如单选/多选/增删的情况，都是使用中介者模式，adapter作为中介者，ViewHolder都注册给它，adapter可以直接操纵每一个ViewHolder视图甚至增删，ViewHolder的各种事件都通知Adapter去处理，adapter提供业务接口给外部使用。

O。O  为何称朱大

**Comment by chaxin** [comment]
- - 好像是在简书还是在哪儿看到一篇介绍开源项目的文章上是这样称呼的，我猜是因为Jude的读音吧。

**Comment by Jude95** [comment]
(ಥ_ಥ) 后辈承受不起...还有什么问题没。
