### ISSUE TITLE
EasyRecyclerView 可以支持item列表项滑动显示操作菜单么

### ISSUE THREAD

**Issue by zhaocz2015** [Jude95/EasyRecyclerView#37]
就像这个项目一样，https://github.com/baoyongzhang/SwipeMenuListView，这个项目不带刷新的效果

**Comment by Jude95** [comment]
呃~对于这些拓展效果。还没有进行支持。
如果打算支持，也不会像这个库的做法。这个Item的效果与RecyclerView无关。
应该会打算另外做一个View库来实现滑动菜单的效果。然后使用者把View放进RecyclerView或者其他地方都可以。
可能过段时间再实现了。

**Comment by zhaocz2015** [comment]
OK TKS
