### ISSUE TITLE
下拉刷新&加载更多重大bug

### ISSUE THREAD

**Issue by jackom** [Jude95/EasyRecyclerView#38]
```
  当前界面的item个数如果不超过屏幕高度，例如当前界面只有两个item显示，会不断地执行“加载更多”回调，直到当前界面item过数超过屏幕高度，麻烦fix一下，谢谢！
```

**Comment by Jude95** [comment]
我能说这标题吓我一跳吗？半夜跳起来看你的问题。

回调了加载更多是正常的。你就只有2个item需要显示，那为什么每次回调你都添加了数据？你添加数据那我不是就应该认为还有下一页数据？理所应当再来次回调吧？
加入空数组/List与自己手动stopMore就会停止加载更多。回调时你应该在没有数据的时候主动停止加载更多。
