### ISSUE TITLE
问下新版本能不能加一个StickHeader，就是悬浮分组，类似通讯录ABCD那样的

### ISSUE THREAD

**Issue by ggchxx** [Jude95/EasyRecyclerView#39]
问下新版本能不能加一个StickHeader，就是悬浮分组，类似通讯录ABCD那样的，现在自己添加了一个 但是用起来麻烦些，看下能否整合到这里面来

**Comment by Jude95** [comment]
这个库并没有打算对工具类需求做太多特定场景的支持。毕竟需求太多。这些UI/交互自定义程度很高，我做了也难以得到所有人认同。

**Comment by ggchxx** [comment]
好的 ，收到。理解哈，谢了。
