### ISSUE TITLE
getalldata的位置问题

### ISSUE THREAD

**Issue by lumina0o0** [Jude95/EasyRecyclerView#41]
我getviewtype是根据每一项中的type来判断，所以在adapter里面需要getalldata，但是有个问题

我不知道应该在哪里getalldata才比较合理，我现在是在getviewtype时给list赋值，这样的话，每一次getviewtype的时候都会给list赋值，感觉很不合理，但是我又不明白应该在哪里赋值才比较好

我在adapter外调用了addall，和insertall两个方法，但是如果要在这两个方法里面getalldata的话，就需要重写他们，我设想过在notify时get，但似乎不行

希望大家可以提供一些想法

**Comment by Jude95** [comment]
我觉得你的语言表达有些乏力。。没能理解，贴下代码吧？
getalldata并不推荐使用(本来就不想开这个API，绝对会出现一大堆代码设计问题)。数据应该由你自己管理。Adapter所管理的数据是内部实现只负责Adapter的View展示(意思是Adapter应该只是一个ArrayList副本与UI绑定)。不应该将数据管理的责任交给Adapter。
getviewtype的模式我也做过很多了。直接getItem(position)再判断类型不就好了？像demo一样...

**Comment by lumina0o0** [comment]
的确是！原来我之前都没有仔细看！！！我已经不知道怎么吐槽自己才好了(ಥ _ ಥ)
