### ISSUE TITLE
貌似不支持GridLayoutManager啊

### ISSUE THREAD

**Issue by zaaach** [Jude95/EasyRecyclerView#45]

**Comment by Jude95** [comment]
你问我支持不支持，我说支持。我就明确告诉你这一点。我感觉你们还需要仔细看Readme。

**Comment by lunarriver** [comment]
魔法少年..

**Comment by zaaach** [comment]
改为Grid形式，上拉加载更多布局的位置有问题。。

**Comment by Jude95** [comment]
可以贴一张有问题的图吗。
我这边是没有问题的。
![image](https://cloud.githubusercontent.com/assets/7901171/15698163/259e376a-27f4-11e6-96f9-2276e0ffbdc9.png)
![image](https://cloud.githubusercontent.com/assets/7901171/15698165/2f190838-27f4-11e6-81a6-ac26737e9344.png)

**Comment by zaaach** [comment]
![qq 20160601134832](https://cloud.githubusercontent.com/assets/9695127/15699495/decf231a-27ff-11e6-9b2d-0c963ff63d41.png)
![qq 20160601134852](https://cloud.githubusercontent.com/assets/9695127/15699496/ded8fb60-27ff-11e6-824d-a7a5399edc39.png)

**Comment by Jude95** [comment]
都说了好好看Readme。
![image](https://cloud.githubusercontent.com/assets/7901171/15699729/cf3a44b4-2801-11e6-863a-d41bc4e6711d.png)

**Comment by zaaach** [comment]
好吧，还真没有看到(⊙﹏⊙)b
