### ISSUE TITLE
能写成一个ViewGroup吗？里面可以兼容其它的第三方或者官方的view

### ISSUE THREAD

**Issue by zhaohuaxiaoy** [Jude95/EasyRecyclerView#48]
现在这个已经足够的好了，只是提一下可能以后会用到的功能

**Comment by Jude95** [comment]
虽然没太明白你的意思。FrameLayout就是对ViewGroup加了一点布局的功能。我继承ViewGroup还是要自己布局...
设计上来说，这个库是对RecyclerView在特定情景的优化封装。牺牲部分拓展性提高特定情景的开发效率。现在这个库虽然提供了很多功能，但拓展性已经很弱了...每次都新需求改代码。新需求改代码...
