### ISSUE TITLE
progress这个view能居中吗？，现在是match_parent让它全屏，背景无法弄成透明的怎么办

### ISSUE THREAD

**Issue by zhaohuaxiaoy** [Jude95/EasyRecyclerView#51]
如题

**Comment by Jude95** [comment]
包裹这些View的是FrameLayout。给你的View设置android:layout_gravity="center"就好了。
其实是透明的。只是我把其他View隐藏了。一般不会想要层叠显示吧？

**Comment by zhaohuaxiaoy** [comment]
我看到代码里把所有view隐藏了，我手动把所有隐藏注释了，我需要在载入的时候RecyclerView和Progress同时显示，居中问题解决了，感谢
