### ISSUE TITLE
about StaggeredGridLayout

### ISSUE THREAD

**Issue by junchenChow** [Jude95/EasyRecyclerView#52]
用StaggeredGridLayout模式的时候 滑动速度快 item显示就出问题了 不知道作者有没有试过 还有就是'StaggeredGridLayoutManager.HORIZONTAL'有header的时候也有问题～

**Comment by Jude95** [comment]
开发过很多次。
滑动速度快 item显示有什么问题？
'StaggeredGridLayoutManager.HORIZONTAL'有header的时候有什么问题。
...你得描述问题啊

**Comment by junchenChow** [comment]
你在demo上没发现吗  滑动速度稍微快一点  图片就会有错乱  不是adapter里面没有tag的那种错乱 ，是有图片就直接贴在边缘不动了，你可以在瀑布流的时候多添加一些数据看看。HORIZONTAL的时候应该也是类似的问题

**Comment by junchenChow** [comment]
![28](https://cloud.githubusercontent.com/assets/13553319/16070054/6e84527c-3305-11e6-8674-a6627f2a37d5.png)

**Comment by junchenChow** [comment]
还是上图看的比较明确～ 就是来回滑动时候产生的 红色标记就是那些错乱贴附在边缘的图片
![b5330d34-6530-4563-83c5-9732877d4490](https://cloud.githubusercontent.com/assets/13553319/16070186/2c7166ee-3306-11e6-94c0-a6693aec380f.png)

**Comment by junchenChow** [comment]
![Uploading 4FE09EBE-3754-41B9-A7B3-F82131A8C99C.png…]()

**Comment by Jude95** [comment]
发现了。。跟黏在屏幕上了一样。。表示第一次遇到这种情况。正在尽力查找。
你知道原因吗。这个问题我现在毫无头绪。

**Comment by Jude95** [comment]
查清楚了。Glide的bug。你换成RecyclerView一样这样。= =

**Comment by junchenChow** [comment]
glide 还有这个毛病呀 哈哈 这几天一直在修自己项目的bug
