### ISSUE TITLE
使用gridview布局  加载更多布局不能居中

### ISSUE THREAD

**Issue by ximencx** [Jude95/EasyRecyclerView#55]
如题

**Comment by Jude95** [comment]
![image](https://cloud.githubusercontent.com/assets/7901171/16103354/6807db26-33aa-11e6-92c6-49a8812eb585.png)
好好看Readme好嘛。= =

**Comment by ximencx** [comment]
@Jude95 嗯嗯 tkx，还遇到一个问题，，底色是白色 第一次加载时不显示progress进度，，设置参照demo写的，，是不是progress颜色重了？

**Comment by ximencx** [comment]
@Jude95  刚才尝试讲progress设置了背景还是不显示  代码中也是调用recycleview.withadapter

**Comment by Jude95** [comment]
setAdapterWithProgress()?Adapter里一开始没有数据吧。然后一直到添加数据。不要调用notifyDataSetChange()。一更新数据就会取消显示Progress。
demo就很正常吧。

**Comment by ximencx** [comment]
@Jude95 按照楼主说的 我试了造成这个的原因是adapte.clear而取消动画的。demo中是延迟1000ms，所以这个操作放在里面会有1000中的显示。我解决方法就是，把clear操作放在异步进程填充数据前。

**Comment by Jude95** [comment]
嗯。本来就应该填充数据前才clear。不然刷新会空白一段时间。
