### ISSUE TITLE
list去重问题

### ISSUE THREAD

**Issue by guoyoujin** [Jude95/EasyRecyclerView#56]
能否实现list里面的对象去重复数据？还是直接重写对象的equas方法就可以实现？不过貌似只有set集合才有这个特性。但是我使用set集合并且对象重写equals的时候还是不能去重，而且set集合是无序的，不知道你有没有什么好的解决方法

**Comment by Jude95** [comment]
我觉得已经实现了一个ArrayList常用的大部分API。建议你添加数据前先去重。或者使用remove手动去重。
Adapter不管理数据。我所持有的数据是为了UI显示必要。请自己管理数据。

**Comment by guoyoujin** [comment]
好吧，因为我感觉这个去重应该是大多数需求都要求做的。不过在addall的时候去重也差不多，就是多了一个对象的引用，很感谢你的回答
