### ISSUE TITLE
How to set data source for EasyRecyclerView ?

### ISSUE THREAD

**Issue by tuanth89** [Jude95/EasyRecyclerView#58]
Hi, thank for lib awesome!
I have datasource. when i refresh, i want to update datasource but don't call clear and add all. Just update datasource and notifydatasetchanged. How ???
Thanks.

**Comment by Jude95** [comment]
The ‘update’ is what mean？
adapter.getItem(position).setXXX()&adapter.notifyDataSetChanged()?
or
adapter.remove(position)&adapter.insert(object,position)?

**Comment by tuanth89** [comment]
@Jude95  Thank for reply
The update mean when i refresh, data can be changed. I just want update data of Adapter, not call Clear or AddAll (this clear all data and add data again of Adapter)
Sorry my bad english :)
Thank.

**Comment by tuanth89** [comment]
@Jude95 Which way to resolve this ?
i just want update list "mObjects" in EasyRecyclerView, because when i clear and addall, my list scroll to top not current view

**Comment by Jude95** [comment]
edit the data directly by `adapter.getItem(position).xxxx` and
![image](https://cloud.githubusercontent.com/assets/7901171/16268958/0939697a-38c3-11e6-90aa-eae62601ab11.png)

**Comment by tuanth89** [comment]
@Jude95 : thanks
so when case many position of data be changed ??? i refresh and i don't know position of data changed. i don't want to use for loop each item of data to set change.

**Comment by Jude95** [comment]
you can't change the data array in adapter.but you can change the data anytime,and call notify.
you can hold the array before add to adapter.

**Comment by tuanth89** [comment]
@Jude95 
No way to change data array after add to adapter ??? Can support set again data array after add to adapter ? Ex :

> public class CategoryNewAdapter extends RecyclerView.Adapter<RowViewHolder> {  
>  private List<Page> mPages;  
>     public CategoryNewAdapter(Context context, List<Page> pages) { 
> mPages = pages; 
>  }
>      public void setDataAfterRefresh(List<Page> pages) { 
> mPages = page ;
>        notifyDataSetChanged();   
> }

**Comment by Jude95** [comment]
= =.I design the adapter's API like ArrayList.and treat the adapter as ArrayList.You obviously can't change the array in ArrayList.
why you want change data array?the API of adapter is complete enough.
or you can use your own adapter with EasyRecyclerView.

**Comment by fangligang1994** [comment]
首先，感谢作者开源。我是一个菜鸟，用到这个库来看看问题。很多人评论一句谢谢都没用，感觉好奇怪。作者辛苦了，希望自己以后也能开源这么好的项目。
