### ISSUE TITLE
添加了header，但list的数据为空就不显示了？

### ISSUE THREAD

**Issue by ximida** [Jude95/EasyRecyclerView#59]
如题，我添加了header，但有时会遇到adapter里面的数据为空，但这时header也是不显示的？

**Comment by Jude95** [comment]
如果你设置了header。并希望不管有没有数据都要显示。那还干嘛设置emptyview。
所以你设置了emptyview我就优先考虑emptyview的逻辑。
无论如何。你都可以showEmpty/showRecycler。来手动控制。

**Comment by ximida** [comment]
好的，明白，谢谢
