### ISSUE TITLE
导入Android Studio后报错

### ISSUE THREAD

**Issue by zhengxiaochuan** [Jude95/EasyRecyclerView#6]
我把代码clone下来导入到Android Studio中就报下面的错，不知道怎么回事啊？

Error:Unable to find method 'org.gradle.api.internal.project.ProjectInternal.getPluginManager()Lorg/gradle/api/internal/plugins/PluginManagerInternal;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by zhengxiaochuan** [comment]
这个问题我已经解决了，也是在github上找到原因的。因为你使用了android maven插件，所以gradle应该是2.4版本的，于是我修改了项目中的gradle-wrapper.properties文件中的distributionUrl修改成了下面的内容：
distributionUrl=https://services.gradle.org/distributions/gradle-2.4-all.zip

这样一句话，然后就可以build了。

if you use the version 1.3 of the plugin then you should be using gradle 2.4

**Comment by Jude95** [comment]
恩。对。其实我用的是2.9版本的。。
