### ISSUE TITLE
error when try to run the demo app

### ISSUE THREAD

**Issue by navotera** [Jude95/EasyRecyclerView#60]
i got error when trying compile the source demo file 
here the error : 

[http://i.imgur.com/UekN9eZ.jpg]

thanks

**Comment by Jude95** [comment]
android studio 2.1+  and Gradle 2.10+  ?

**Comment by navotera** [comment]
ANdroid studio ver 2.1.1
Gradle 2.10

**Comment by Jude95** [comment]
try update the buildTool or support library SDK?
or compare the gradle file with your other project?
I think it is a problem of your local gradle config.

**Comment by navotera** [comment]
thanks for your response i try it ..
