### ISSUE TITLE
如何在Viewholder的改造中使用Butterknife

### ISSUE THREAD

**Issue by gmfbilu** [Jude95/EasyRecyclerView#69]

**Comment by Jude95** [comment]
参考这里：
https://github.com/Jude95/Automobile/blob/master/app/src/main/java/com/jude/automobile/ui/viewholder/AssembleViewHolder.java

**Comment by gmfbilu** [comment]
这个控件不是真正的recycleview，那么它的性能怎么样呢，比如item数量很多，图片很多

来自 魅族 PRO 5

-------- 原始邮件 --------
发件人：Jude notifications@github.com
时间：周三 7月20日 11:49
收件人：Jude95/EasyRecyclerView EasyRecyclerView@noreply.github.com
抄送：gmfbilu gmfbilu@hotmail.com,Author author@noreply.github.com
主题：Re: [Jude95/EasyRecyclerView] 如何在Viewholder的改造中使用Butterknife (#69)

**Comment by Jude95** [comment]
他不是真正的recycleview意思是，我包裹了一个RecyclerView。这些都是真正的RecyclerView处理的。

**Comment by gmfbilu** [comment]
大神，在下拉刷新的时候，adapter.clear后会显示一下加载错误的条目，然后数据才回加载上来，这样怎么让他不显示啊

来自 魅族 PRO 5

-------- 原始邮件 --------
发件人：Jude notifications@github.com
时间：周三 7月20日 14:19
收件人：Jude95/EasyRecyclerView EasyRecyclerView@noreply.github.com
抄送：gmfbilu gmfbilu@hotmail.com,Author author@noreply.github.com
主题：Re: [Jude95/EasyRecyclerView] 如何在Viewholder的改造中使用Butterknife (#69)

**Comment by Jude95** [comment]
什么鬼，为什么会显示加载错误。你看看demo有问题吗。

**Comment by gmfbilu** [comment]
当条目不足一屏幕时，最后一个条目下面没有显示nomore的layout。还有一种情况是网速很慢的情况下会自动加载的同时用户也可以触发下拉刷新

来自 魅族 PRO 5

-------- 原始邮件 --------
发件人：Jude notifications@github.com
时间：周三 7月20日 21:50
收件人：Jude95/EasyRecyclerView EasyRecyclerView@noreply.github.com
抄送：gmfbilu gmfbilu@hotmail.com,Author author@noreply.github.com
主题：Re: [Jude95/EasyRecyclerView] 如何在Viewholder的改造中使用Butterknife (#69)

**Comment by gmfbilu** [comment]
首次进去的时候加载完毕后没有更多不显示，但是还是占了一个item的位置

来自 魅族 PRO 5

-------- 原始邮件 --------
发件人：gmfbilu gmfbilu@hotmail.com
时间：周三 7月20日 22:11
收件人：Jude95/EasyRecyclerView reply@reply.github.com
主题：Re: [Jude95/EasyRecyclerView] 如何在Viewholder的改造中使用Butterknife (#69)
