### ISSUE TITLE
当使用gridlayoutmanager时加载更多显示问题

### ISSUE THREAD

**Issue by yihuxz** [Jude95/EasyRecyclerView#7]
很感谢分享，使用起来确实很方便。但是在实际使用中发现了点问题，当使用gridlayoutmanager或者staggeredgridlayoutmanager，上拉加载更多的布局有点错乱了。不知道该怎么解决的？

**Comment by Jude95** [comment]
确实对于那种布局，这种header与footer的实现就不再适合了。我也在寻找适合grid和错位的header与footer的实现。。grid还好，staggeredgridlayoutmanager完美实现好难。。

**Comment by yihuxz** [comment]
目前想的临时方案是，在gridlayoutmanager模式时通过RecyclerView.OnScrollListener来判断是否滑动到底部，如果滑动到底部的话，则调用onRefresh根据自定义标志位来判断是刷新数据还是加载数据。先试试行不行，嘿嘿。

**Comment by Jude95** [comment]
呃，只是触发事件的话，设一个空白的moreview就可以了。要完美显示“加载更多”的View略难。

**Comment by reaper12** [comment]
可以参照https://github.com/jianghejie/XRecyclerView 这个来弄

**Comment by Jude95** [comment]
看看最新版本有什么问题没？Header与Footer支持了gridlayoutmanager和staggeredgridlayoutmanager。抱歉最近有些忙。

**Comment by yihuxz** [comment]
ok了，在新项目中使用了~感觉这种实现用起来真的蛮方便的~~~哈哈
