### ISSUE TITLE
安卓4.1，4.0的都发生inflateException

### ISSUE THREAD

**Issue by gmfbilu** [Jude95/EasyRecyclerView#71]

**Comment by allenz8512** [comment]
安卓4.2以下的View构造器会调用setPadding，EasyRecyclerView覆盖了并调用了mRecycler.setPadding，而这个时候mRecycler未初始化，求修正

**Comment by gmfbilu** [comment]
这个非要作者来修改吗

**Comment by Jude95** [comment]
谢谢指出。4.0.5已修改，试试还有没有问题吧。出了这么严重的问题很抱歉。个人项目做不到全面测试。不过有问题一定尽快修复。

**Comment by gmfbilu** [comment]
哈哈，谢谢你才对啊，我们开发自己写会出现更多的bug，而且时间也来不及。对了4.0.5什么时候出来啊，我好测试一下

来自 魅族 PRO 5

-------- 原始邮件 --------
发件人：Jude notifications@github.com
时间：周六 7月23日 11:48
收件人：Jude95/EasyRecyclerView EasyRecyclerView@noreply.github.com
抄送：gmfbilu gmfbilu@hotmail.com,Author author@noreply.github.com
主题：Re: [Jude95/EasyRecyclerView] 安卓4.1，4.0的都发生inflateException (#71)

**Comment by Jude95** [comment]
好了。。才发现向github的push竟然失败了。
