### ISSUE TITLE
非正常 No adapter attached; skipping layout

### ISSUE THREAD

**Issue by xingyufeifan** [Jude95/EasyRecyclerView#77]
首先这个错误并没有使我的RecyclerView无法加载数据，相反，他显示的很好。
我使用RxJava返回参数
 `.observeOn(AndroidSchedulers.mainThread())
                .subscribeOn(Schedulers.newThread());`
在返回参数之前出现了这两个/E
我找不到其他原因了，请问RecyclerView在线程的处理是否有什么需要注意的地方？
或是因为其他原因

**Comment by Jude95** [comment]
不用担心。这句TAG没有只是提示一下。
源码在此：  
![image](https://cloud.githubusercontent.com/assets/7901171/17424686/fe017bee-5af8-11e6-8790-ff2f1c8e6d2d.png)
当RecyclerView被layout的时候，还没有设置Adapter就会提示。如果你是延迟设置Adapter的。后面设置就好。没有影响。
