### ISSUE TITLE
怎样隐藏滚动条？

### ISSUE THREAD

**Issue by zczhzy** [Jude95/EasyRecyclerView#81]
android:scrollbars="none"
这样写没用

**Comment by Jude95** [comment]
app:scrollbars="none"

**Comment by weilixing00** [comment]
对的  同问  这样设置之后  滚动条依旧存在

**Comment by zczhzy** [comment]
我设置之后，已经能隐藏了 @weilixing00

**Comment by weilixing00** [comment]
哦  我命名空间写错了  写成android:了 既然这个问题解决了  就关了吧  这个控件确实很不错  @zczhzy
