### ISSUE TITLE
setError的view的点击触发事件是自己加的，但是并不会响应，这个该如何解决呢？

### ISSUE THREAD

**Issue by endingocean** [Jude95/EasyRecyclerView#82]
如题，在setError时，是否可以给该view也直接添加点击事件

**Comment by Jude95** [comment]
返回的就是View。你设就好了。

**Comment by endingocean** [comment]
mAdapter.setError(R.layout.empty_error).setOnClickListener(xxx);
与
mAdapter.setError(R.layout.empty_error);
mRecyclerView.getErrorView().setOnClickListener(xxx);
这两个处理方式上，上方那个直接返回的view并不能响应这个点击事件，而下方的却可以，这个不知道是怎么造成的

**Comment by Jude95** [comment]
你是2个一起设的？因为setError返回的是一个包裹ErrorView的Container。你再给ErrorView设个监听。就冲突了。只会响应子View。
