### ISSUE TITLE
当数据不足一屏幕时 设置setmore方法会自动加载重复数据直到铺满一屏幕

### ISSUE THREAD

**Issue by zilingyao** [Jude95/EasyRecyclerView#83]
如果此时下拉刷新  则数据消失  然后又自动加载至一屏幕  请问怎么设置不自动加载？上拉加载更多时再加载

**Comment by Jude95** [comment]
看看这个 #28

**Comment by zilingyao** [comment]
多谢多谢

**Comment by zilingyao** [comment]
为什么有的条目下边的分割线不显示

**Comment by zilingyao** [comment]
![image](https://cloud.githubusercontent.com/assets/16448548/18075130/c900ae00-6ea4-11e6-8461-6233c0069c6a.png)

**Comment by Jude95** [comment]
新的问题请提新issue
