### ISSUE TITLE
EasyRecyclerView与ScrollView滑动冲突的问题

### ISSUE THREAD

**Issue by guiying712** [Jude95/EasyRecyclerView#88]
两者结合在一起使用时，滑动会有很大的阻尼感，没法流畅的滑动。

**Comment by Jude95** [comment]
讲道理，在你很清楚事件处理逻辑前，不要这样用。不知道你具体配置，不过这样用一般都会造成RecyclerView失效变成LinearLayout

**Comment by guiying712** [comment]
```
        这个问题我已经用自定义scrollview解决，感谢你的回复。Sent from Mail Master
        在2016年09月19日 12:28，Jude 写道:讲道理，在你很清楚事件处理逻辑前，不要这样用。不知道你具体配置，不过这样用一般都会造成RecyclerView失效变成LinearLayout
```

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Jude95/EasyRecyclerView","title":"Jude95/EasyRecyclerView","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Jude95/EasyRecyclerView"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Jude95 in #88: 讲道理，在你很清楚事件处理逻辑前，不要这样用。不知道你具体配置，不过这样用一般都会造成RecyclerView失效变成LinearLayout"}],"action":{"name":"View Issue","url":"https://github.com/Jude95/EasyRecyclerView/issues/88#issuecomment-247909654"}}}
