### ISSUE TITLE
貌似不支持多类型itemview，以及绑定数据setdata()没有传入position无法自由获取position对象？

### ISSUE THREAD

**Issue by YanceyLee** [Jude95/EasyRecyclerView#9]
如何设置多类型的itemview，如何对setdata()的自由设值（有关联的item）？

**Comment by Jude95** [comment]
多类型itemview看看demo(刚加的)。
设计上是给你什么数据你生成什么View。而不是你为了生成某个View而去寻找XX数据。
View是与你的数据列表一一对应的。你的数据列表可以是很多种数据，ViewHolder也可以是很多种。

**Comment by Jude95** [comment]
没有问题的话，就关闭这个issue了。
