### ISSUE TITLE
item 里面有水平滑动的控件时，有冲突，很难滑动

### ISSUE THREAD

**Issue by followztx** [Jude95/EasyRecyclerView#90]
1、item 里面有水平滑动的控件时，很难水平滑动；
2、建议修改SwipeRefreshLayout的事件拦截，只有dy>dx时，才竖直滑动；
而，现在的SwipeRefreshLayout是通过布局里面写死的，
`
        View v = LayoutInflater.from(getContext()).inflate(R.layout.layout_progress_recyclerview, this);
`
`<com.jude.easyrecyclerview.swipe.SwipeRefreshLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/ptr_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<android.support.v7.widget.RecyclerView
    android:id="@android:id/list"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clickable="true"
    android:scrollbars="vertical|horizontal"/>

<FrameLayout
    android:id="@+id/empty"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clickable="true"
    />

<FrameLayout
    android:id="@+id/progress"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clickable="true"
    />

<FrameLayout
    android:id="@+id/error"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clickable="true"
    />
```

</com.jude.easyrecyclerview.swipe.SwipeRefreshLayout>`

有什么方法，可以替换成子类么

**Comment by followztx** [comment]
修改源码：将EasyRecyclerView里面的com.jude.easyrecyclerview.swipe.SwipeRefreshLayout替换成VerticalSwipeRefreshLayout(继承v4包的SwipeRefreshLayout）

`package com.jude.easyrecyclerview.swipe;

import android.content.Context;
import android.support.v4.widget.SwipeRefreshLayout;
import android.util.AttributeSet;
import android.view.MotionEvent;
import android.view.ViewConfiguration;

public class VerticalSwipeRefreshLayout extends SwipeRefreshLayout {

```
private int scaleTouchSlop;
private float preX;

public VerticalSwipeRefreshLayout(Context context, AttributeSet attrs) {
    super(context, attrs);
    scaleTouchSlop = ViewConfiguration.get(context).getScaledTouchSlop();
}

@Override
public boolean onInterceptTouchEvent(MotionEvent ev) {
    switch (ev.getAction()) {
        case MotionEvent.ACTION_DOWN:

            preX = ev.getX();
            break;

        case MotionEvent.ACTION_MOVE:
            float instanceX = Math.abs(ev.getX() - preX);

            // 容差值大概是24，再加上60
            if (instanceX > scaleTouchSlop + 60) {
                return false;
            }
            break;
    }
    return super.onInterceptTouchEvent(ev);
}
```

}
`

**Comment by Jude95** [comment]
我记得我自定义SwipeRefreshLayout。设置为不拦截事件。他的手势处理都是捡RecyclerView没有处理的事件去处理。所以横向手势没问题。我测试ViewPager也没问题。。为什么你会觉得有问题。是不是你的处理手势的View没有消耗事件。
