### ISSUE TITLE
每个item 中的控件，想要点击事件的话，需要自己写回调吗？  

### ISSUE THREAD

**Issue by masite** [Jude95/EasyRecyclerView#92]

**Comment by Jude95** [comment]
这看你自己的代码设计了。不过我常用设计是，事件直接在Viewholder里处理

**Comment by masite** [comment]
如果直接在view holder中写事件，那如何调用到该activity中的方法或者变量啊，感觉极不方便

**Comment by Jude95** [comment]
事件总线，订阅等，而在优秀的设计下这些都不是问题。你说的问题在RecyclerView上依然存在。应该好好想想代码改怎样设计。

**Comment by masite** [comment]
我用eventbus,可以解决这个问题，
