### ISSUE TITLE
GridLayoutManager时加载更多不能整行显示好像是加到了一个item里

### ISSUE THREAD

**Issue by stevenMieMie** [Jude95/EasyRecyclerView#93]
GridLayoutManager时加载更多不能整行显示好像是加到了一个item里，怎么能像LinearLayoutManager一样正常加到底部。

**Comment by Jude95** [comment]
![image](https://cloud.githubusercontent.com/assets/7901171/18459824/5f4048f8-799f-11e6-8f78-ab416e461916.png)
