### ISSUE TITLE
下拉刷新跟加载更多问题 求助

### ISSUE THREAD

**Issue by lengqingfeng2012** [Jude95/EasyRecyclerView#94]
你好 有个问题 我现在只有一条数据 设置了setmore方法  初始状态就会加载更多 问题是 我如果在加载更多的时候又下拉刷新 这样就会出现一条重复数据 一闪而过 请问这个应该怎么解决啊 搞了好长时间了  求助

**Comment by Jude95** [comment]
下拉刷新时请取消掉加载更多的那次请求。

**Comment by lengqingfeng2012** [comment]
设置stopmore吗  不管用啊

**Comment by Jude95** [comment]
是你自己发出的网络请求或异步加载请求。使他不再回调adapter.add
