### ISSUE TITLE
打包时，提示Multiple dex files define Landriod/support/v7/widget/AdapterHelper

### ISSUE THREAD

**Issue by masite** [Jude95/EasyRecyclerView#98]
问一下，加入这个compile'com.jude:easyrecyclerview:4.0.2'  这个依赖后，  需要去除V7包吗？ 我打包时除了
![image](https://cloud.githubusercontent.com/assets/13652316/18630636/76e9d4be-7ea0-11e6-8d04-4c384a5404e6.png)    这个个错误，

**Comment by masite** [comment]
解决了，我把 compile files('libs/android-support-v7-recyclerview.jar')系统的这个注掉就行了。。  再问一下，每次用到easyrecylerview，都需要创建一个adapter，但这个adapter就除了return new SearchTypeTwoHolder(parent); 这么一句之外，其他都是重复 ，你看有没有办法，不用这么麻烦，

**Comment by Jude95** [comment]
你是说这样？

``` java
        recyclerView.setAdapter(new RecyclerArrayAdapter(this) {
            @Override
            public BaseViewHolder OnCreateViewHolder(ViewGroup parent, int viewType) {
                return new PersonViewHolder(parent);
            }
        });
```

没问题的啊。本来就是这样设计的。这样已经算是很简单的抽象类了吧。只是因为Adapter有大量方法，而且需要穿Context在构造函数。所以不能再简化成接口了。

...issue不是论坛，新问题请新建issue
