### ISSUE TITLE
使用4.2.0的StaggeredGridLayoutManager报数组越界异常

### ISSUE THREAD

**Issue by Kuohui** [Jude95/EasyRecyclerView#99]
错误如题，使用4.0.6时不会出现此问题，找不到原因，上来问问
![2016-09-21_154634](https://cloud.githubusercontent.com/assets/17747848/18702202/32314414-8013-11e6-8cc8-58695116472c.png)
![2016-09-21_154717](https://cloud.githubusercontent.com/assets/17747848/18702209/385e03c2-8013-11e6-87aa-bec0d7da8748.png)

**Comment by Jude95** [comment]
试了很久，没能复现这个bug。你能详细描述一下或提供完整代码？能提供一个出现crash的demo就更感谢。

**Comment by Jude95** [comment]
Resolved
